// web_ui/block_definitions.js

// Autogenerated Blockly Block Definitions

// MOD block
Blockly.Blocks['MOD_BLOCK'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("MOD:");
    this.appendDummyInput().appendField(new Blockly.FieldTextInput("MyGameMode"), "MOD_NAME");
    this.appendDummyInput().appendField("Description:").appendField(new Blockly.FieldTextInput("Description"), "DESCRIPTION");
    this.setPreviousStatement(false, null);
    this.setNextStatement(true, "Rule");
    this.appendStatementInput("RULES_CONDITIONS_SUBROUTINES").setCheck(["Rule", "Condition", "Subroutine"]).appendField("Game Parameters:");
    this.setDeletable(false);
    this.setMovable(false);
    this.setColour('#4A4A4A');
    this.setTooltip("The root container for all game logic. Add rules, conditions, and subroutines to set game map parameters.");
    this.setHelpUrl("");
  }
};

// RULE_HEADER block
Blockly.Blocks['RULE_HEADER'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("RULE");
    this.appendDummyInput().appendField(new Blockly.FieldTextInput("New Rule"), "RULE_NAME");
    this.appendDummyInput().appendField("Event Type:").appendField(new Blockly.FieldDropdown([["Ongoing", "ONGOING"], ["OnPlayerJoin", "ON_PLAYER_JOIN"], ["OnPlayerDeath", "ON_PLAYER_DEATH"], ["OnPlayerSpawn", "ON_PLAYER_SPAWN"]]), "EVENT_TYPE");
    this.appendDummyInput().appendField("Scope:").appendField(new Blockly.FieldDropdown([["Global", "GLOBAL"], ["Team", "TEAM"], ["Squad", "SQUAD"], ["Player", "PLAYER"]]), "SCOPE");
    this.setPreviousStatement(true, "Rule");
    this.setNextStatement(true, "Rule");
    this.appendStatementInput("CONDITIONS").setCheck("Condition").appendField("Conditions:");
    this.appendStatementInput("ACTIONS").setCheck(["Action", "SubroutineReference", "ControlAction"]).appendField("Actions:");
    this.setColour('#A285E6');
    this.setTooltip("Defines a game rule with CONDITIONS and ACTIONS.");
    this.setHelpUrl("");
  }
};

// Placeholder "Condition" block
Blockly.Blocks['CONDITION_BLOCK'] = {
  init: function() {
    this.appendDummyInput().appendField("Condition");
    this.setPreviousStatement(true, "Condition");
    this.setNextStatement(true, "Condition");
    this.setColour('#45B5B5');
    this.setTooltip("A placeholder condition block.");
    this.setHelpUrl("");
  }
};

// Placeholder "Action" block
Blockly.Blocks['ACTION_BLOCK'] = {
  init: function() {
    this.appendDummyInput().appendField("Action");
    this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");
    this.setColour('#B5A045');
    this.setTooltip("A placeholder action block.");
    this.setHelpUrl("");
  }
};

// Placeholder "SUBROUTINE:" block
Blockly.Blocks['SUBROUTINE_BLOCK'] = {
  init: function() {
    this.appendDummyInput().appendField("SUBROUTINE:");
    this.appendDummyInput().appendField(new Blockly.FieldTextInput("New Subroutine"), "SUBROUTINE_NAME");
    this.appendStatementInput("ACTIONS_CONDITIONS")
        .setCheck(["Action", "Condition"])
        .appendField("Logic:");
    this.setColour('#E6A85C');
    this.setPreviousStatement(false, null);
    this.setNextStatement(false, null);
    this.setTooltip("Reusable logic blocks that can be called from multiple places.");
    this.setHelpUrl("");
  }
};

// Placeholder "Call Subroutine:" block
Blockly.Blocks['SUBROUTINE_REFERENCE_BLOCK'] = {
  init: function() {
    this.appendDummyInput().appendField("Call Subroutine:").appendField(new Blockly.FieldTextInput("Subroutine Name"), "SUBROUTINE_REF_NAME");
    this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");
    this.setColour('#E6A85C');
    this.setTooltip("Calls a defined subroutine.");
    this.setHelpUrl("");
  }
};

// Placeholder "Control Action:" block
Blockly.Blocks['CONTROL_ACTION_BLOCK'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Control Action:");
    this.appendDummyInput().appendField(new Blockly.FieldTextInput("Action Type"), "ACTION_TYPE");
    this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");
    this.setColour('#A285E6'); // Purple (same as rules for now)
    this.setTooltip("A placeholder control action block.");
    this.setHelpUrl("");
  }
};
// Autogenerated Blockly Block Definitions


// AIBATTLEFIELD_BEHAVIOR block
Blockly.Blocks['AIBATTLEFIELD_BEHAVIOR'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("AI Battlefield Behavior");
    this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");
    this.setColour('#D32F2F');
    this.setTooltip("Sets the AI to standard battlefield combat behavior");
    this.setHelpUrl("");
  }
};

// AI_DEFEND_POSITION_BEHAVIOR block
Blockly.Blocks['AIDEFEND_POSITION_BEHAVIOR'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("AI Defend Position Behavior");
    this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Position:").appendField(new Blockly.FieldTextInput(""), "POSITION");
    this.appendDummyInput().appendField("Radius:").appendField(new Blockly.FieldTextInput(""), "RADIUS");
    this.appendDummyInput().appendField("Time:").appendField(new Blockly.FieldTextInput(""), "TIME");
    this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");
    this.setColour('#D32F2F');
    this.setTooltip("Orders AI to defend a specific area");
    this.setHelpUrl("");
  }
};

// AI_IDLE_BEHAVIOR block
Blockly.Blocks['AI_IDLE_BEHAVIOR'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("AI Idle Behavior");
    this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");
    this.setColour('#D32F2F');
    this.setTooltip("Sets the AI to idle state");
    this.setHelpUrl("");
  }
};

// AI_MOVE_TO_BEHAVIOR block
Blockly.Blocks['AI_MOVE_TO_BEHAVIOR'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("AI Move To Behavior");
    this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Position:").appendField(new Blockly.FieldTextInput(""), "POSITION");
    this.appendDummyInput().appendField("Sprint:").appendField(new Blockly.FieldTextInput(""), "SPRINT");
    this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");
    this.setColour('#D32F2F');
    this.setTooltip("Orders AI to move to a location");
    this.setHelpUrl("");
  }
};

// AI_PARACHUTE_BEHAVIOR block
Blockly.Blocks['AI_PARACHUTE_BEHAVIOR'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("AI Parachute Behavior");
    this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");
    this.setColour('#D32F2F');
    this.setTooltip("Orders AI to deploy parachute");
    this.setHelpUrl("");
  }
};

// AI_WAYPOINT_IDLE_BEHAVIOR block
Blockly.Blocks['AI_WAYPOINT_IDLE_BEHAVIOR'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("AI Waypoint Idle Behavior");
    this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Time:").appendField(new Blockly.FieldTextInput(""), "TIME");
    this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");
    this.setColour('#D32F2F');
    this.setTooltip("AI waits at a waypoint for a duration");
    this.setHelpUrl("");
  }
};

// AI_FOLLOW_PLAYER block
Blockly.Blocks['AI_FOLLOW_PLAYER'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("AI Follow Player");
    this.appendDummyInput().appendField("Ai_Player:").appendField(new Blockly.FieldTextInput(""), "AI_PLAYER");
    this.appendDummyInput().appendField("Target_Player:").appendField(new Blockly.FieldTextInput(""), "TARGET_PLAYER");
    this.appendDummyInput().appendField("Distance:").appendField(new Blockly.FieldTextInput(""), "DISTANCE");
    this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");
    this.setColour('#D32F2F');
    this.setTooltip("Orders AI to follow a specific player");
    this.setHelpUrl("");
  }
};

// AI_HOLD_POSITION block
Blockly.Blocks['AI_HOLD_POSITION'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("AI Hold Position");
    this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");
    this.setColour('#D32F2F');
    this.setTooltip("Orders AI to hold their current position");
    this.setHelpUrl("");
  }
};

// AI_ATTACK_TARGET block
Blockly.Blocks['AI_ATTACK_TARGET'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("AI Attack Target");
    this.appendDummyInput().appendField("Ai_Player:").appendField(new Blockly.FieldTextInput(""), "AI_PLAYER");
    this.appendDummyInput().appendField("Target_Player:").appendField(new Blockly.FieldTextInput(""), "TARGET_PLAYER");
    this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");
    this.setColour('#D32F2F');
    this.setTooltip("Orders AI to attack a specific target");
    this.setHelpUrl("");
  }
};

// SET_AI_BEHAVIOR block
Blockly.Blocks['SET_AI_BEHAVIOR'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set AI Behavior");
    this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Behavior_Mode:").appendField(new Blockly.FieldTextInput(""), "BEHAVIOR_MODE");
    this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");
    this.setColour('#D32F2F');
    this.setTooltip("Sets the general behavior mode for the AI");
    this.setHelpUrl("");
  }
};

// DEPLOY_AI block
Blockly.Blocks['DEPLOY_AI'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Deploy AI");
    this.appendDummyInput().appendField("Team:").appendField(new Blockly.FieldTextInput(""), "TEAM");
    this.appendDummyInput().appendField("Soldier_Type:").appendField(new Blockly.FieldTextInput(""), "SOLDIER_TYPE");
    this.appendDummyInput().appendField("Position:").appendField(new Blockly.FieldTextInput(""), "POSITION");
    this.appendDummyInput().appendField("Kit:").appendField(new Blockly.FieldTextInput(""), "KIT");
    this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");
    this.setColour('#D32F2F');
    this.setTooltip("Spawns a new AI soldier");
    this.setHelpUrl("");
  }
};

// DESPAWN_AI block
Blockly.Blocks['DESPAWN_AI'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Despawn AI");
    this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");
    this.setColour('#D32F2F');
    this.setTooltip("Removes an AI soldier from the game");
    this.setHelpUrl("");
  }
};

// SET_AI_SPAWN_LOCATION block
Blockly.Blocks['SET_AI_SPAWN_LOCATION'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set AI Spawn Location");
    this.appendDummyInput().appendField("Team:").appendField(new Blockly.FieldTextInput(""), "TEAM");
    this.appendDummyInput().appendField("Position:").appendField(new Blockly.FieldTextInput(""), "POSITION");
    this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");
    this.setColour('#D32F2F');
    this.setTooltip("Sets where AI soldiers will spawn");
    this.setHelpUrl("");
  }
};

// SET_AI_HEALTH block
Blockly.Blocks['SET_AI_HEALTH'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set AI Health");
    this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Amount:").appendField(new Blockly.FieldTextInput(""), "AMOUNT");
    this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");
    this.setColour('#D32F2F');
    this.setTooltip("Sets the health of an AI soldier");
    this.setHelpUrl("");
  }
};

// SET_AI_TEAM block
Blockly.Blocks['SET_AI_TEAM'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set AI Team");
    this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Team_ID:").appendField(new Blockly.FieldTextInput(""), "TEAM_ID");
    this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");
    this.setColour('#D32F2F');
    this.setTooltip("Changes the team of an AI soldier");
    this.setHelpUrl("");
  }
};

// GET_AI_HEALTH block
Blockly.Blocks['GET_AI_HEALTH'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get AI Health");
    this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.setOutput(true, null);
    this.setColour('#D32F2F');
    this.setTooltip("Returns the current health of an AI soldier");
    this.setHelpUrl("");
  }
};

// GET_AI_TEAM block
Blockly.Blocks['GET_AI_TEAM'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get AI Team");
    this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.setOutput(true, null);
    this.setColour('#D32F2F');
    this.setTooltip("Returns the team ID of an AI soldier");
    this.setHelpUrl("");
  }
};

// AI_IS_ALIVE block
Blockly.Blocks['AI_IS_ALIVE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("AI Is Alive");
    this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.setOutput(true, null);
    this.setColour('#D32F2F');
    this.setTooltip("Checks if an AI soldier is currently alive");
    this.setHelpUrl("");
  }
};

// CREATE_ARRAY block
Blockly.Blocks['CREATE_ARRAY'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Create Array");
    this.setOutput(true, null);
    this.setColour('#0097A7');
    this.setTooltip("Creates an empty array.");
    this.setHelpUrl("");
  }
};

// ARRAY_LENGTH block
Blockly.Blocks['ARRAY_LENGTH'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Array Length");
    this.appendDummyInput().appendField("Array:").appendField(new Blockly.FieldTextInput(""), "ARRAY");
    this.setOutput(true, null);
    this.setColour('#0097A7');
    this.setTooltip("Returns the number of elements in an array.");
    this.setHelpUrl("");
  }
};

// GET_ELEMENT block
Blockly.Blocks['GET_ELEMENT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get Element");
    this.appendDummyInput().appendField("Array:").appendField(new Blockly.FieldTextInput(""), "ARRAY");
    this.appendDummyInput().appendField("Index:").appendField(new Blockly.FieldTextInput(""), "INDEX");
    this.setOutput(true, null);
    this.setColour('#0097A7');
    this.setTooltip("Returns the element at a specific index in an array.");
    this.setHelpUrl("");
  }
};

// SET_ELEMENT block
Blockly.Blocks['SET_ELEMENT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set Element");
    this.appendDummyInput().appendField("Array:").appendField(new Blockly.FieldTextInput(""), "ARRAY");
    this.appendDummyInput().appendField("Index:").appendField(new Blockly.FieldTextInput(""), "INDEX");
    this.appendDummyInput().appendField("Value:").appendField(new Blockly.FieldTextInput(""), "VALUE");
    this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");
    this.setColour('#0097A7');
    this.setTooltip("Sets the element at a specific index in an array.");
    this.setHelpUrl("");
  }
};

// APPEND_TO_ARRAY block
Blockly.Blocks['APPEND_TO_ARRAY'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Append To Array");
    this.appendDummyInput().appendField("Array:").appendField(new Blockly.FieldTextInput(""), "ARRAY");
    this.appendDummyInput().appendField("Value:").appendField(new Blockly.FieldTextInput(""), "VALUE");
    this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");
    this.setColour('#0097A7');
    this.setTooltip("Adds a value to the end of an array.");
    this.setHelpUrl("");
  }
};

// REMOVE_FROM_ARRAY block
Blockly.Blocks['REMOVE_FROM_ARRAY'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Remove From Array");
    this.appendDummyInput().appendField("Array:").appendField(new Blockly.FieldTextInput(""), "ARRAY");
    this.appendDummyInput().appendField("Index:").appendField(new Blockly.FieldTextInput(""), "INDEX");
    this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");
    this.setColour('#0097A7');
    this.setTooltip("Removes an element from an array at a specific index.");
    this.setHelpUrl("");
  }
};

// FIND_FIRST block
Blockly.Blocks['FIND_FIRST'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Find First");
    this.appendDummyInput().appendField("Array:").appendField(new Blockly.FieldTextInput(""), "ARRAY");
    this.appendDummyInput().appendField("Value:").appendField(new Blockly.FieldTextInput(""), "VALUE");
    this.setOutput(true, null);
    this.setColour('#0097A7');
    this.setTooltip("Finds the first index of a value in an array. Returns -1 if not found.");
    this.setHelpUrl("");
  }
};

// SORT_ARRAY block
Blockly.Blocks['SORT_ARRAY'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Sort Array");
    this.appendDummyInput().appendField("Array:").appendField(new Blockly.FieldTextInput(""), "ARRAY");
    this.appendDummyInput().appendField("Order:").appendField(new Blockly.FieldTextInput(""), "ORDER");
    this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");
    this.setColour('#0097A7');
    this.setTooltip("Sorts an array in ascending or descending order.");
    this.setHelpUrl("");
  }
};

// AUDIOLOADMUSIC block
Blockly.Blocks['AUDIOLOADMUSIC'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("LoadMusic");
    this.appendDummyInput().appendField("Music_ID:").appendField(new Blockly.FieldTextInput(""), "MUSIC_ID");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#455A64');
    this.setTooltip("Loads music given an ID.");
    this.setHelpUrl("");
  }
};

// AUDIOPLAYMUSIC block
Blockly.Blocks['AUDIOPLAYMUSIC'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("PlayMusic");
    this.appendDummyInput().appendField("Music_ID:").appendField(new Blockly.FieldTextInput(""), "MUSIC_ID");
    this.appendDummyInput().appendField("Players:").appendField(new Blockly.FieldTextInput(""), "PLAYERS");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#455A64');
    this.setTooltip("Plays music given an ID for specific players.");
    this.setHelpUrl("");
  }
};

// AUDIOSETMUSICPARAM block
Blockly.Blocks['AUDIOSETMUSICPARAM'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("SetMusicParam");
    this.appendDummyInput().appendField("Music_ID:").appendField(new Blockly.FieldTextInput(""), "MUSIC_ID");
    this.appendDummyInput().appendField("Param:").appendField(new Blockly.FieldTextInput(""), "PARAM");
    this.appendDummyInput().appendField("Players:").appendField(new Blockly.FieldTextInput(""), "PLAYERS");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#455A64');
    this.setTooltip("Sets a parameter for music for specific players.");
    this.setHelpUrl("");
  }
};

// AUDIOUNLOADMUSIC block
Blockly.Blocks['AUDIOUNLOADMUSIC'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("UnloadMusic");
    this.appendDummyInput().appendField("Music_ID:").appendField(new Blockly.FieldTextInput(""), "MUSIC_ID");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#455A64');
    this.setTooltip("Unloads music given an ID.");
    this.setHelpUrl("");
  }
};

// AUDIOPLAYSOUND block
Blockly.Blocks['AUDIOPLAYSOUND'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("PlaySound");
    this.appendDummyInput().appendField("Sound_ID:").appendField(new Blockly.FieldTextInput(""), "SOUND_ID");
    this.appendDummyInput().appendField("Position:").appendField(new Blockly.FieldTextInput(""), "POSITION");
    this.appendDummyInput().appendField("Players:").appendField(new Blockly.FieldTextInput(""), "PLAYERS");
    this.appendDummyInput().appendField("Volume:").appendField(new Blockly.FieldTextInput(""), "VOLUME");
    this.appendDummyInput().appendField("Pitch:").appendField(new Blockly.FieldTextInput(""), "PITCH");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#455A64');
    this.setTooltip("Plays a sound at a position for specific players.");
    this.setHelpUrl("");
  }
};

// AUDIOPLAYVO block
Blockly.Blocks['AUDIOPLAYVO'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("PlayVO");
    this.appendDummyInput().appendField("Vo_ID:").appendField(new Blockly.FieldTextInput(""), "VO_ID");
    this.appendDummyInput().appendField("Speaker:").appendField(new Blockly.FieldTextInput(""), "SPEAKER");
    this.appendDummyInput().appendField("Listener:").appendField(new Blockly.FieldTextInput(""), "LISTENER");
    this.appendDummyInput().appendField("Players:").appendField(new Blockly.FieldTextInput(""), "PLAYERS");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#455A64');
    this.setTooltip("Plays a voice over for specific players.");
    this.setHelpUrl("");
  }
};

// AUDIOSTOPSOUND block
Blockly.Blocks['AUDIOSTOPSOUND'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("StopSound");
    this.appendDummyInput().appendField("Sound_ID:").appendField(new Blockly.FieldTextInput(""), "SOUND_ID");
    this.appendDummyInput().appendField("Players:").appendField(new Blockly.FieldTextInput(""), "PLAYERS");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#455A64');
    this.setTooltip("Stops a sound for specific players.");
    this.setHelpUrl("");
  }
};

// CAMERASETPLAYERCAMERA block
Blockly.Blocks['CAMERASETPLAYERCAMERA'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set Player Camera");
    this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Camera_Mode:").appendField(new Blockly.FieldTextInput(""), "CAMERA_MODE");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#37474F');
    this.setTooltip("Sets the camera mode for a specific player");
    this.setHelpUrl("");
  }
};

// CAMERALOCKCAMERATOTARGET block
Blockly.Blocks['CAMERALOCKCAMERATOTARGET'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Lock Camera to Target");
    this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Target:").appendField(new Blockly.FieldTextInput(""), "TARGET");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#37474F');
    this.setTooltip("Locks the player's camera to look at a target");
    this.setHelpUrl("");
  }
};

// CAMERACAMERASHAKE block
Blockly.Blocks['CAMERACAMERASHAKE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Camera Shake");
    this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Intensity:").appendField(new Blockly.FieldTextInput(""), "INTENSITY");
    this.appendDummyInput().appendField("Duration:").appendField(new Blockly.FieldTextInput(""), "DURATION");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#37474F');
    this.setTooltip("Applies a shake effect to the player's camera");
    this.setHelpUrl("");
  }
};

// CAMERASETCAMERAFOV block
Blockly.Blocks['CAMERASETCAMERAFOV'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set Camera FOV");
    this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Fov:").appendField(new Blockly.FieldTextInput(""), "FOV");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#37474F');
    this.setTooltip("Sets the Field of View for the player's camera");
    this.setHelpUrl("");
  }
};

// CAMERARESETCAMERA block
Blockly.Blocks['CAMERARESETCAMERA'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Reset Camera");
    this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#37474F');
    this.setTooltip("Resets the player's camera to default");
    this.setHelpUrl("");
  }
};

// CAMERAFIRSTPERSONCAMERA block
Blockly.Blocks['CAMERAFIRSTPERSONCAMERA'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("First Person Camera");
    this.setOutput(true, null);
    this.setColour('#37474F');
    this.setTooltip("First person camera mode");
    this.setHelpUrl("");
  }
};

// CAMERATHIRDPERSONCAMERA block
Blockly.Blocks['CAMERATHIRDPERSONCAMERA'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Third Person Camera");
    this.setOutput(true, null);
    this.setColour('#37474F');
    this.setTooltip("Third person camera mode");
    this.setHelpUrl("");
  }
};

// CAMERAFREECAMERA block
Blockly.Blocks['CAMERAFREECAMERA'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Free Camera");
    this.setOutput(true, null);
    this.setColour('#37474F');
    this.setTooltip("Free camera mode");
    this.setHelpUrl("");
  }
};

// CAMERASPECTATORCAMERA block
Blockly.Blocks['CAMERASPECTATORCAMERA'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Spectator Camera");
    this.setOutput(true, null);
    this.setColour('#37474F');
    this.setTooltip("Spectator camera mode");
    this.setHelpUrl("");
  }
};

// Equal block
Blockly.Blocks['EQUAL'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Equal");
    this.appendDummyInput().appendField("A:").appendField(new Blockly.FieldTextInput(""), "A");
    this.appendDummyInput().appendField("B:").appendField(new Blockly.FieldTextInput(""), "B");
    this.setOutput(true, null);
    this.setColour('#1976D2');
    this.setTooltip("Returns True if inputs are equal");
    this.setHelpUrl("");
  }
};

// Not Equal block
Blockly.Blocks['NOT_EQUAL'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Not Equal");
    this.appendDummyInput().appendField("A:").appendField(new Blockly.FieldTextInput(""), "A");
    this.appendDummyInput().appendField("B:").appendField(new Blockly.FieldTextInput(""), "B");
    this.setOutput(true, null);
    this.setColour('#1976D2');
    this.setTooltip("Returns True if inputs are not equal");
    this.setHelpUrl("");
  }
};

// Less Than block
Blockly.Blocks['LESS_THAN'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Less Than");
    this.appendDummyInput().appendField("A:").appendField(new Blockly.FieldTextInput(""), "A");
    this.appendDummyInput().appendField("B:").appendField(new Blockly.FieldTextInput(""), "B");
    this.setOutput(true, null);
    this.setColour('#1976D2');
    this.setTooltip("Returns True if A < B");
    this.setHelpUrl("");
  }
};

// Less Than Or Equal block
Blockly.Blocks['LESS_THAN_OR_EQUAL'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Less Than Or Equal");
    this.appendDummyInput().appendField("Value_A:").appendField(new Blockly.FieldTextInput(""), "VALUE_A");
    this.appendDummyInput().appendField("Value_B:").appendField(new Blockly.FieldTextInput(""), "VALUE_B");
    this.setPreviousStatement(true, "Condition");
    this.setNextStatement(true, "Condition");
    this.setColour('#45B5B5');
    this.setTooltip("Returns true if A is less than or equal to B");
    this.setHelpUrl("");
  }
};

// Greater Than block
Blockly.Blocks['GREATER_THAN'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Greater Than");
    this.appendDummyInput().appendField("A:").appendField(new Blockly.FieldTextInput(""), "A");
    this.appendDummyInput().appendField("B:").appendField(new Blockly.FieldTextInput(""), "B");
    this.setOutput(true, null);
    this.setColour('#1976D2');
    this.setTooltip("Returns True if A > B");
    this.setHelpUrl("");
  }
};

// Greater Than Or Equal block
Blockly.Blocks['GREATER_THAN_OR_EQUAL'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Greater Than Or Equal");
    this.appendDummyInput().appendField("Value_A:").appendField(new Blockly.FieldTextInput(""), "VALUE_A");
    this.appendDummyInput().appendField("Value_B:").appendField(new Blockly.FieldTextInput(""), "VALUE_B");
    this.setPreviousStatement(true, "Condition");
    this.setNextStatement(true, "Condition");
    this.setColour('#45B5B5');
    this.setTooltip("Returns true if A is greater than or equal to B");
    this.setHelpUrl("");
  }
};

// Play Effect block
Blockly.Blocks['PLAY_EFFECT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Play Effect");
    this.appendDummyInput().appendField("Effect_Type:").appendField(new Blockly.FieldTextInput(""), "EFFECT_TYPE");
    this.appendDummyInput().appendField("Location:").appendField(new Blockly.FieldTextInput(""), "LOCATION");
    this.appendDummyInput().appendField("Scale:").appendField(new Blockly.FieldTextInput(""), "SCALE");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#263238');
    this.setTooltip("Plays a visual effect at a location");
    this.setHelpUrl("");
  }
};

// Stop Effect block
Blockly.Blocks['STOP_EFFECT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Stop Effect");
    this.appendDummyInput().appendField("Effect_ID:").appendField(new Blockly.FieldTextInput(""), "EFFECT_ID");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#263238');
    this.setTooltip("Stops a playing effect");
    this.setHelpUrl("");
  }
};

// Particle Effect block
Blockly.Blocks['PARTICLE_EFFECT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Particle Effect");
    this.appendDummyInput().appendField("Particle_Type:").appendField(new Blockly.FieldTextInput(""), "PARTICLE_TYPE");
    this.setOutput(true, null);
    this.setColour('#263238');
    this.setTooltip("Returns a particle effect type");
    this.setHelpUrl("");
  }
};

// Explosion Effect block
Blockly.Blocks['EXPLOSION_EFFECT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Explosion Effect");
    this.appendDummyInput().appendField("Explosion_Type:").appendField(new Blockly.FieldTextInput(""), "EXPLOSION_TYPE");
    this.setOutput(true, null);
    this.setColour('#263238');
    this.setTooltip("Returns an explosion effect type");
    this.setHelpUrl("");
  }
};

// Screen Flash block
Blockly.Blocks['SCREEN_FLASH'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Screen Flash");
    this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Color:").appendField(new Blockly.FieldTextInput(""), "COLOR");
    this.appendDummyInput().appendField("Duration:").appendField(new Blockly.FieldTextInput(""), "DURATION");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#263238');
    this.setTooltip("Flashes the player's screen with a color");
    this.setHelpUrl("");
  }
};

// Screen Fade block
Blockly.Blocks['SCREEN_FADE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Screen Fade");
    this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Fade_Type:").appendField(new Blockly.FieldTextInput(""), "FADE_TYPE");
    this.appendDummyInput().appendField("Duration:").appendField(new Blockly.FieldTextInput(""), "DURATION");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#263238');
    this.setTooltip("Fades the player's screen");
    this.setHelpUrl("");
  }
};

// Apply Screen Filter block
Blockly.Blocks['APPLY_SCREEN_FILTER'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Apply Screen Filter");
    this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Filter_Type:").appendField(new Blockly.FieldTextInput(""), "FILTER_TYPE");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#263238');
    this.setTooltip("Applies a visual filter to the player's screen");
    this.setHelpUrl("");
  }
};

// DeployEmplacement block
Blockly.Blocks['DEPLOY_EMPLACEMENT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("DeployEmplacement");
    this.appendDummyInput().appendField("Emplacement_ID:").appendField(new Blockly.FieldTextInput(""), "EMPLACEMENT_ID");
    this.appendDummyInput().appendField("Position:").appendField(new Blockly.FieldTextInput(""), "POSITION");
    this.appendDummyInput().appendField("Rotation:").appendField(new Blockly.FieldTextInput(""), "ROTATION");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#8D6E63');
    this.setTooltip("");
    this.setHelpUrl("");
  }
};

// ON_GAME_START block
Blockly.Blocks['ON_GAME_START'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("On Game Start");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#5D4037');
    this.setTooltip("");
    this.setHelpUrl("");
  }
};

// ON_PLAYER_JOIN block
Blockly.Blocks['ON_PLAYER_JOIN'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("On Player Join");
    this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#5D4037');
    this.setTooltip("");
    this.setHelpUrl("");
  }
};

// EVENT_ATTACKER block
Blockly.Blocks['EVENT_ATTACKER'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Event Attacker");
    this.setOutput(true, null);
    this.setColour('#5D4037');
    this.setTooltip("The player who caused the event (e.g. the killer)");
    this.setHelpUrl("");
  }
};

// EVENT_DAMAGE block
Blockly.Blocks['EVENT_DAMAGE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Event Damage");
    this.setOutput(true, null);
    this.setColour('#5D4037');
    this.setTooltip("The amount of damage dealt in the event");
    this.setHelpUrl("");
  }
};

// EVENT_LOCATION block
Blockly.Blocks['EVENT_LOCATION'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Event Location");
    this.setOutput(true, null);
    this.setColour('#5D4037');
    this.setTooltip("The location where the event occurred");
    this.setHelpUrl("");
  }
};

// EVENT_PLAYER block
Blockly.Blocks['EVENT_PLAYER'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Event Player");
    this.setOutput(true, null);
    this.setColour('#5D4037');
    this.setTooltip("The primary player involved in the event");
    this.setHelpUrl("");
  }
};

// EVENT_TEAM block
Blockly.Blocks['EVENT_TEAM'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Event Team");
    this.setOutput(true, null);
    this.setColour('#5D4037');
    this.setTooltip("The team involved in the event");
    this.setHelpUrl("");
  }
};

// EVENT_VICTIM block
Blockly.Blocks['EVENT_VICTIM'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Event Victim");
    this.setOutput(true, null);
    this.setColour('#5D4037');
    this.setTooltip("The player who was the victim of the event");
    this.setHelpUrl("");
  }
};

// EVENT_WEAPON block
Blockly.Blocks['EVENT_WEAPON'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Event Weapon");
    this.setOutput(true, null);
    this.setColour('#5D4037');
    this.setTooltip("The weapon used in the event");
    this.setHelpUrl("");
  }
};

// GET_GAMEMODE block
Blockly.Blocks['GET_GAMEMODE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get Gamemode");
    this.setOutput(true, null);
    this.setColour('#5D4037');
    this.setTooltip("Gets the current gamemode.");
    this.setHelpUrl("");
  }
};

// SET_GAMEMODE block
Blockly.Blocks['SET_GAMEMODE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set Gamemode");
    this.appendDummyInput().appendField("Gamemode:").appendField(new Blockly.FieldTextInput(""), "GAMEMODE");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#5D4037');
    this.setTooltip("Sets the current gamemode.");
    this.setHelpUrl("");
  }
};

// ENABLE_FRIENDLY_FIRE block
Blockly.Blocks['ENABLE_FRIENDLY_FIRE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Enable Friendly Fire");
    this.appendDummyInput().appendField("Enabled:").appendField(new Blockly.FieldTextInput(""), "ENABLED");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#5D4037');
    this.setTooltip("Enables or disables friendly fire.");
    this.setHelpUrl("");
  }
};

// SET_SCORE block
Blockly.Blocks['SET_SCORE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set Score");
    this.appendDummyInput().appendField("Team:").appendField(new Blockly.FieldTextInput(""), "TEAM");
    this.appendDummyInput().appendField("Score:").appendField(new Blockly.FieldTextInput(""), "SCORE");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#5D4037');
    this.setTooltip("Sets the score for a team.");
    this.setHelpUrl("");
  }
};

// GET_SCORE block
Blockly.Blocks['GET_SCORE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get Score");
    this.appendDummyInput().appendField("Team:").appendField(new Blockly.FieldTextInput(""), "TEAM");
    this.setOutput(true, null);
    this.setColour('#5D4037');
    this.setTooltip("Gets the score for a team.");
    this.setHelpUrl("");
  }
};

// SET_TIME_LIMIT block
Blockly.Blocks['SET_TIME_LIMIT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set Time Limit");
    this.appendDummyInput().appendField("Time_Limit:").appendField(new Blockly.FieldTextInput(""), "TIME_LIMIT");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#5D4037');
    this.setTooltip("Sets the time limit for the round.");
    this.setHelpUrl("");
  }
};

// GET_TIME_LIMIT block
Blockly.Blocks['GET_TIME_LIMIT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get Time Limit");
    this.setOutput(true, null);
    this.setColour('#5D4037');
    this.setTooltip("Gets the time limit for the round.");
    this.setHelpUrl("");
  }
};

// WAIT block
Blockly.Blocks['WAIT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Wait");
    this.appendDummyInput().appendField("Seconds:").appendField(new Blockly.FieldTextInput(""), "SECONDS");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#1976D2');
    this.setTooltip("Pauses execution for a specified time");
    this.setHelpUrl("");
  }
};

// WAIT_UNTIL block
Blockly.Blocks['WAIT_UNTIL'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Wait Until");
    this.appendDummyInput().appendField("Condition:").appendField(new Blockly.FieldTextInput(""), "CONDITION");
    this.appendDummyInput().appendField("Timeout:").appendField(new Blockly.FieldTextInput(""), "TIMEOUT");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#1976D2');
    this.setTooltip("Pauses execution until condition is true");
    this.setHelpUrl("");
  }
};

// BREAK block
Blockly.Blocks['BREAK'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Break");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#1976D2');
    this.setTooltip("Exits the current loop immediately");
    this.setHelpUrl("");
  }
};

// CONTINUE block
Blockly.Blocks['CONTINUE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Continue");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#1976D2');
    this.setTooltip("Skips to the next iteration of the current loop");
    this.setHelpUrl("");
  }
};

// IF block
Blockly.Blocks['IF'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("If");
    this.appendDummyInput().appendField("Condition:").appendField(new Blockly.FieldTextInput(""), "CONDITION");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#1976D2');
    this.setTooltip("Executes nested blocks if condition is true");
    this.setHelpUrl("");
  }
};

// WHILE block
Blockly.Blocks['WHILE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("While");
    this.appendDummyInput().appendField("Condition:").appendField(new Blockly.FieldTextInput(""), "CONDITION");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#1976D2');
    this.setTooltip("Repeats nested blocks while condition is true");
    this.setHelpUrl("");
  }
};

// AND block
Blockly.Blocks['AND'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("And");
    this.appendDummyInput().appendField("A:").appendField(new Blockly.FieldTextInput(""), "A");
    this.appendDummyInput().appendField("B:").appendField(new Blockly.FieldTextInput(""), "B");
    this.setOutput(true, null);
    this.setColour('#1976D2');
    this.setTooltip("Returns True if both inputs are True");
    this.setHelpUrl("");
  }
};

// OR block
Blockly.Blocks['OR'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Or");
    this.appendDummyInput().appendField("A:").appendField(new Blockly.FieldTextInput(""), "A");
    this.appendDummyInput().appendField("B:").appendField(new Blockly.FieldTextInput(""), "B");
    this.setOutput(true, null);
    this.setColour('#1976D2');
    this.setTooltip("Returns True if either input is True");
    this.setHelpUrl("");
  }
};

// NOT block
Blockly.Blocks['NOT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Not");
    this.appendDummyInput().appendField("A:").appendField(new Blockly.FieldTextInput(""), "A");
    this.setOutput(true, null);
    this.setColour('#1976D2');
    this.setTooltip("Returns the opposite boolean value");
    this.setHelpUrl("");
  }
};

// TRUE block
Blockly.Blocks['TRUE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("True");
    this.setOutput(true, null);
    this.setColour('#1976D2');
    this.setTooltip("Boolean True value");
    this.setHelpUrl("");
  }
};

// FALSE block
Blockly.Blocks['FALSE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("False");
    this.setOutput(true, null);
    this.setColour('#1976D2');
    this.setTooltip("Boolean False value");
    this.setHelpUrl("");
  }
};

// GREATER_THAN_EQUAL block
Blockly.Blocks['GREATER_THAN_EQUAL'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Greater Than Or Equal");
    this.appendDummyInput().appendField("A:").appendField(new Blockly.FieldTextInput(""), "A");
    this.appendDummyInput().appendField("B:").appendField(new Blockly.FieldTextInput(""), "B");
    this.setOutput(true, null);
    this.setColour('#1976D2');
    this.setTooltip("Returns True if A >= B");
    this.setHelpUrl("");
  }
};

// LESS_THAN_EQUAL block
Blockly.Blocks['LESS_THAN_EQUAL'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Less Than Or Equal");
    this.appendDummyInput().appendField("A:").appendField(new Blockly.FieldTextInput(""), "A");
    this.appendDummyInput().appendField("B:").appendField(new Blockly.FieldTextInput(""), "B");
    this.setOutput(true, null);
    this.setColour('#1976D2');
    this.setTooltip("Returns True if A <= B");
    this.setHelpUrl("");
  }
};

// FOR_VARIABLE block
Blockly.Blocks['FOR_VARIABLE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("ForVariable");
    this.appendDummyInput().appendField("From_Value:").appendField(new Blockly.FieldTextInput(""), "FROM_VALUE");
    this.appendDummyInput().appendField("To_Value:").appendField(new Blockly.FieldTextInput(""), "TO_VALUE");
    this.appendDummyInput().appendField("By_Value:").appendField(new Blockly.FieldTextInput(""), "BY_VALUE");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#1976D2');
    this.setTooltip("Loops from starting value to ending value by increment");
    this.setHelpUrl("");
  }
};

// ADD block
Blockly.Blocks['ADD'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Add");
    this.appendDummyInput().appendField("Value_A:").appendField(new Blockly.FieldTextInput(""), "VALUE_A");
    this.appendDummyInput().appendField("Value_B:").appendField(new Blockly.FieldTextInput(""), "VALUE_B");
    this.setOutput(true, null);
    this.setColour('#1976D2');
    this.setTooltip("Returns the sum of A and B");
    this.setHelpUrl("");
  }
};

// SUBTRACT block
Blockly.Blocks['SUBTRACT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Subtract");
    this.appendDummyInput().appendField("Value_A:").appendField(new Blockly.FieldTextInput(""), "VALUE_A");
    this.appendDummyInput().appendField("Value_B:").appendField(new Blockly.FieldTextInput(""), "VALUE_B");
    this.setOutput(true, null);
    this.setColour('#1976D2');
    this.setTooltip("Returns the difference of A and B");
    this.setHelpUrl("");
  }
};

// MULTIPLY block
Blockly.Blocks['MULTIPLY'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Multiply");
    this.appendDummyInput().appendField("Value_A:").appendField(new Blockly.FieldTextInput(""), "VALUE_A");
    this.appendDummyInput().appendField("Value_B:").appendField(new Blockly.FieldTextInput(""), "VALUE_B");
    this.setOutput(true, null);
    this.setColour('#1976D2');
    this.setTooltip("Returns the product of A and B");
    this.setHelpUrl("");
  }
};

// DIVIDE block
Blockly.Blocks['DIVIDE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Divide");
    this.appendDummyInput().appendField("Value_A:").appendField(new Blockly.FieldTextInput(""), "VALUE_A");
    this.appendDummyInput().appendField("Value_B:").appendField(new Blockly.FieldTextInput(""), "VALUE_B");
    this.setOutput(true, null);
    this.setColour('#1976D2');
    this.setTooltip("Returns the quotient of A and B");
    this.setHelpUrl("");
  }
};

// POWER block
Blockly.Blocks['POWER'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Power");
    this.appendDummyInput().appendField("Base:").appendField(new Blockly.FieldTextInput(""), "BASE");
    this.appendDummyInput().appendField("Exponent:").appendField(new Blockly.FieldTextInput(""), "EXPONENT");
    this.setOutput(true, null);
    this.setColour('#1976D2');
    this.setTooltip("Returns the base to the exponent power.");
    this.setHelpUrl("");
  }
};

// SQUARE_ROOT block
Blockly.Blocks['SQUARE_ROOT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Square Root");
    this.appendDummyInput().appendField("Value:").appendField(new Blockly.FieldTextInput(""), "VALUE");
    this.setOutput(true, null);
    this.setColour('#1976D2');
    this.setTooltip("Returns the square root of a number.");
    this.setHelpUrl("");
  }
};

// ABSOLUTE block
Blockly.Blocks['ABSOLUTE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Absolute");
    this.appendDummyInput().appendField("Value:").appendField(new Blockly.FieldTextInput(""), "VALUE");
    this.setOutput(true, null);
    this.setColour('#1976D2');
    this.setTooltip("Returns the absolute value of a number.");
    this.setHelpUrl("");
  }
};

// MODULO block
Blockly.Blocks['MODULO'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Modulo");
    this.appendDummyInput().appendField("Dividend:").appendField(new Blockly.FieldTextInput(""), "DIVIDEND");
    this.appendDummyInput().appendField("Divisor:").appendField(new Blockly.FieldTextInput(""), "DIVISOR");
    this.setOutput(true, null);
    this.setColour('#1976D2');
    this.setTooltip("Returns the remainder of a division.");
    this.setHelpUrl("");
  }
};

// SET_OBJECTIVE_STATE block
Blockly.Blocks['SET_OBJECTIVE_STATE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set Objective State");
    this.appendDummyInput().appendField("Objective:").appendField(new Blockly.FieldTextInput(""), "OBJECTIVE");
    this.appendDummyInput().appendField("State:").appendField(new Blockly.FieldTextInput(""), "STATE");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#F9A825');
    this.setTooltip("Sets the state of an objective.");
    this.setHelpUrl("");
  }
};

// GET_OBJECTIVE_STATE block
Blockly.Blocks['GET_OBJECTIVE_STATE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get Objective State");
    this.appendDummyInput().appendField("Objective:").appendField(new Blockly.FieldTextInput(""), "OBJECTIVE");
    this.setOutput(true, null);
    this.setColour('#F9A825');
    this.setTooltip("Gets the state of an objective.");
    this.setHelpUrl("");
  }
};

// COMMENT block
Blockly.Blocks['COMMENT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Comment");
    this.appendDummyInput().appendField("Text:").appendField(new Blockly.FieldTextInput(""), "TEXT");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#9E9E9E');
    this.setTooltip("Adds a comment to the logic for documentation.");
    this.setHelpUrl("");
  }
};

// GET_PLAYER_BY_ID block
Blockly.Blocks['GET_PLAYER_BY_ID'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get Player By Id");
    this.appendDummyInput().appendField("Player_ID:").appendField(new Blockly.FieldTextInput(""), "PLAYER_ID");
    this.setOutput(true, null);
    this.setColour('#C2185B');
    this.setTooltip("Gets a player by their ID.");
    this.setHelpUrl("");
  }
};

// GET_PLAYER_NAME block
Blockly.Blocks['GET_PLAYER_NAME'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get Player Name");
    this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.setOutput(true, null);
    this.setColour('#C2185B');
    this.setTooltip("Gets the name of a player.");
    this.setHelpUrl("");
  }
};

// GET_PLAYER_HEALTH block
Blockly.Blocks['GET_PLAYER_HEALTH'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get Player Health");
    this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.setOutput(true, null);
    this.setColour('#C2185B');
    this.setTooltip("Gets the health of a player.");
    this.setHelpUrl("");
  }
};

// TELEPORT_PLAYER block
Blockly.Blocks['TELEPORT_PLAYER'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Teleport Player");
    this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Position:").appendField(new Blockly.FieldTextInput(""), "POSITION");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#C2185B');
    this.setTooltip("Teleports a player to a specific location.");
    this.setHelpUrl("");
  }
};

// KILL_PLAYER block
Blockly.Blocks['KILL_PLAYER'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Kill Player");
    this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#C2185B');
    this.setTooltip("Kills a player.");
    this.setHelpUrl("");
  }
};

// GET_PLAYER_TEAM block
Blockly.Blocks['GET_PLAYER_TEAM'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get Player Team");
    this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.setOutput(true, null);
    this.setColour('#C2185B');
    this.setTooltip("Gets the team of a player.");
    this.setHelpUrl("");
  }
};

// SET_PLAYER_TEAM block
Blockly.Blocks['SET_PLAYER_TEAM'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set Player Team");
    this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Team:").appendField(new Blockly.FieldTextInput(""), "TEAM");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#C2185B');
    this.setTooltip("Sets the team of a player.");
    this.setHelpUrl("");
  }
};

// CALL_SUBROUTINE block
Blockly.Blocks['CALL_SUBROUTINE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Call Subroutine");
    this.appendDummyInput().appendField("Subroutine_Name:").appendField(new Blockly.FieldDropdown([["NewSubroutine", "NEWSUBROUTINE"]]), "SUBROUTINE_NAME");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#E6A85C');
    this.setTooltip("Executes a subroutine");
    this.setHelpUrl("");
  }
};

// RETURN block
Blockly.Blocks['RETURN'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Return");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#E6A85C');
    this.setTooltip("Returns from the current subroutine");
    this.setHelpUrl("");
  }
};

// VECTOR block
Blockly.Blocks['VECTOR'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Vector");
    this.appendDummyInput().appendField("X:").appendField(new Blockly.FieldTextInput(""), "X");
    this.appendDummyInput().appendField("Y:").appendField(new Blockly.FieldTextInput(""), "Y");
    this.appendDummyInput().appendField("Z:").appendField(new Blockly.FieldTextInput(""), "Z");
    this.setOutput(true, null);
    this.setColour('#212121');
    this.setTooltip("Creates a vector from X, Y, Z components");
    this.setHelpUrl("");
  }
};

// VECTOR_TOWARDS block
Blockly.Blocks['VECTOR_TOWARDS'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Vector Towards");
    this.appendDummyInput().appendField("Start_Pos:").appendField(new Blockly.FieldTextInput(""), "START_POS");
    this.appendDummyInput().appendField("End_Pos:").appendField(new Blockly.FieldTextInput(""), "END_POS");
    this.setOutput(true, null);
    this.setColour('#212121');
    this.setTooltip("Creates a direction vector from start to end");
    this.setHelpUrl("");
  }
};

// DISTANCE_BETWEEN block
Blockly.Blocks['DISTANCE_BETWEEN'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Distance Between");
    this.appendDummyInput().appendField("Position_A:").appendField(new Blockly.FieldTextInput(""), "POSITION_A");
    this.appendDummyInput().appendField("Position_B:").appendField(new Blockly.FieldTextInput(""), "POSITION_B");
    this.setOutput(true, null);
    this.setColour('#212121');
    this.setTooltip("Returns distance between two positions");
    this.setHelpUrl("");
  }
};

// X_COMPONENT_OF block
Blockly.Blocks['X_COMPONENT_OF'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("X Component Of");
    this.appendDummyInput().appendField("Vector:").appendField(new Blockly.FieldTextInput(""), "VECTOR");
    this.setOutput(true, null);
    this.setColour('#212121');
    this.setTooltip("Returns the X component of a vector");
    this.setHelpUrl("");
  }
};

// Y_COMPONENT_OF block
Blockly.Blocks['Y_COMPONENT_OF'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Y Component Of");
    this.appendDummyInput().appendField("Vector:").appendField(new Blockly.FieldTextInput(""), "VECTOR");
    this.setOutput(true, null);
    this.setColour('#212121');
    this.setTooltip("Returns the Y component of a vector");
    this.setHelpUrl("");
  }
};

// Z_COMPONENT_OF block
Blockly.Blocks['Z_COMPONENT_OF'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Z Component Of");
    this.appendDummyInput().appendField("Vector:").appendField(new Blockly.FieldTextInput(""), "VECTOR");
    this.setOutput(true, null);
    this.setColour('#212121');
    this.setTooltip("Returns the Z component of a vector");
    this.setHelpUrl("");
  }
};

// NORMALIZE block
Blockly.Blocks['NORMALIZE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Normalize");
    this.appendDummyInput().appendField("Vector:").appendField(new Blockly.FieldTextInput(""), "VECTOR");
    this.setOutput(true, null);
    this.setColour('#212121');
    this.setTooltip("Returns a normalized vector (length 1)");
    this.setHelpUrl("");
  }
};

// DOT_PRODUCT block
Blockly.Blocks['DOT_PRODUCT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Dot Product");
    this.appendDummyInput().appendField("Vector_A:").appendField(new Blockly.FieldTextInput(""), "VECTOR_A");
    this.appendDummyInput().appendField("Vector_B:").appendField(new Blockly.FieldTextInput(""), "VECTOR_B");
    this.setOutput(true, null);
    this.setColour('#212121');
    this.setTooltip("Returns the dot product of two vectors");
    this.setHelpUrl("");
  }
};

// CROSS_PRODUCT block
Blockly.Blocks['CROSS_PRODUCT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Cross Product");
    this.appendDummyInput().appendField("Vector_A:").appendField(new Blockly.FieldTextInput(""), "VECTOR_A");
    this.appendDummyInput().appendField("Vector_B:").appendField(new Blockly.FieldTextInput(""), "VECTOR_B");
    this.setOutput(true, null);
    this.setColour('#212121');
    this.setTooltip("Returns the cross product of two vectors");
    this.setHelpUrl("");
  }
};

// VECTOR_MAGNITUDE block
Blockly.Blocks['VECTOR_MAGNITUDE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Magnitude Of");
    this.appendDummyInput().appendField("Vector:").appendField(new Blockly.FieldTextInput(""), "VECTOR");
    this.setOutput(true, null);
    this.setColour('#212121');
    this.setTooltip("Returns the length of a vector");
    this.setHelpUrl("");
  }
};

// UP block
Blockly.Blocks['UP'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Up");
    this.setOutput(true, null);
    this.setColour('#212121');
    this.setTooltip("Returns the up direction vector (0, 1, 0)");
    this.setHelpUrl("");
  }
};

// DOWN block
Blockly.Blocks['DOWN'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Down");
    this.setOutput(true, null);
    this.setColour('#212121');
    this.setTooltip("Returns the down direction vector (0, -1, 0)");
    this.setHelpUrl("");
  }
};

// LEFT block
Blockly.Blocks['LEFT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Left");
    this.setOutput(true, null);
    this.setColour('#212121');
    this.setTooltip("Returns the left direction vector (-1, 0, 0)");
    this.setHelpUrl("");
  }
};

// RIGHT block
Blockly.Blocks['RIGHT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Right");
    this.setOutput(true, null);
    this.setColour('#212121');
    this.setTooltip("Returns the right direction vector (1, 0, 0)");
    this.setHelpUrl("");
  }
};

// FORWARD block
Blockly.Blocks['FORWARD'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Forward");
    this.setOutput(true, null);
    this.setColour('#212121');
    this.setTooltip("Returns the forward direction vector (0, 0, 1)");
    this.setHelpUrl("");
  }
};

// BACKWARD block
Blockly.Blocks['BACKWARD'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Backward");
    this.setOutput(true, null);
    this.setColour('#212121');
    this.setTooltip("Returns the backward direction vector (0, 0, -1)");
    this.setHelpUrl("");
  }
};

// SHOW_MESSAGE block
Blockly.Blocks['SHOW_MESSAGE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Show Message");
    this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Message:").appendField(new Blockly.FieldTextInput(""), "MESSAGE");
    this.appendDummyInput().appendField("Duration:").appendField(new Blockly.FieldTextInput(""), "DURATION");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#607D8B');
    this.setTooltip("Shows a message to the player");
    this.setHelpUrl("");
  }
};

// SHOW_BIG_MESSAGE block
Blockly.Blocks['SHOW_BIG_MESSAGE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Show Big Message");
    this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Title:").appendField(new Blockly.FieldTextInput(""), "TITLE");
    this.appendDummyInput().appendField("Subtitle:").appendField(new Blockly.FieldTextInput(""), "SUBTITLE");
    this.appendDummyInput().appendField("Duration:").appendField(new Blockly.FieldTextInput(""), "DURATION");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#607D8B');
    this.setTooltip("Shows a large message on screen");
    this.setHelpUrl("");
  }
};

// SHOW_NOTIFICATION block
Blockly.Blocks['SHOW_NOTIFICATION'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Show Notification");
    this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Text:").appendField(new Blockly.FieldTextInput(""), "TEXT");
    this.appendDummyInput().appendField("Icon:").appendField(new Blockly.FieldTextInput(""), "ICON");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#607D8B');
    this.setTooltip("Shows a notification toast");
    this.setHelpUrl("");
  }
};

// SET_HUD_VISIBLE block
Blockly.Blocks['SET_HUD_VISIBLE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set HUD Visible");
    this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Hud_Element:").appendField(new Blockly.FieldTextInput(""), "HUD_ELEMENT");
    this.appendDummyInput().appendField("Visible:").appendField(new Blockly.FieldTextInput(""), "VISIBLE");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#607D8B');
    this.setTooltip("Shows or hides specific HUD elements");
    this.setHelpUrl("");
  }
};

// UPDATE_HUD_TEXT block
Blockly.Blocks['UPDATE_HUD_TEXT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Update HUD Text");
    this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Hud_ID:").appendField(new Blockly.FieldTextInput(""), "HUD_ID");
    this.appendDummyInput().appendField("Text:").appendField(new Blockly.FieldTextInput(""), "TEXT");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#607D8B');
    this.setTooltip("Updates text on a custom HUD element");
    this.setHelpUrl("");
  }
};

// CREATE_CUSTOM_HUD block
Blockly.Blocks['CREATE_CUSTOM_HUD'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Create Custom HUD");
    this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Hud_Config:").appendField(new Blockly.FieldTextInput(""), "HUD_CONFIG");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#607D8B');
    this.setTooltip("Creates a custom HUD layout");
    this.setHelpUrl("");
  }
};

// CREATE_WORLD_MARKER block
Blockly.Blocks['CREATE_WORLD_MARKER'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Create World Marker");
    this.appendDummyInput().appendField("Location:").appendField(new Blockly.FieldTextInput(""), "LOCATION");
    this.appendDummyInput().appendField("Icon:").appendField(new Blockly.FieldTextInput(""), "ICON");
    this.appendDummyInput().appendField("Text:").appendField(new Blockly.FieldTextInput(""), "TEXT");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#607D8B');
    this.setTooltip("Creates a 3D marker in the world");
    this.setHelpUrl("");
  }
};

// REMOVE_WORLD_MARKER block
Blockly.Blocks['REMOVE_WORLD_MARKER'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Remove World Marker");
    this.appendDummyInput().appendField("Marker_ID:").appendField(new Blockly.FieldTextInput(""), "MARKER_ID");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#607D8B');
    this.setTooltip("Removes a world marker");
    this.setHelpUrl("");
  }
};

// SET_OBJECTIVE_MARKER block
Blockly.Blocks['SET_OBJECTIVE_MARKER'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set Objective Marker");
    this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Location:").appendField(new Blockly.FieldTextInput(""), "LOCATION");
    this.appendDummyInput().appendField("Text:").appendField(new Blockly.FieldTextInput(""), "TEXT");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#607D8B');
    this.setTooltip("Sets the objective marker for a player");
    this.setHelpUrl("");
  }
};

// UPDATE_SCOREBOARD block
Blockly.Blocks['UPDATE_SCOREBOARD'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Update Scoreboard");
    this.appendDummyInput().appendField("Entries:").appendField(new Blockly.FieldTextInput(""), "ENTRIES");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#607D8B');
    this.setTooltip("Updates the scoreboard data");
    this.setHelpUrl("");
  }
};

// SHOW_SCOREBOARD block
Blockly.Blocks['SHOW_SCOREBOARD'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Show Scoreboard");
    this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Visible:").appendField(new Blockly.FieldTextInput(""), "VISIBLE");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#607D8B');
    this.setTooltip("Forces the scoreboard to show or hide");
    this.setHelpUrl("");
  }
};

// NUMBER block
Blockly.Blocks['NUMBER'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Number");
    this.setOutput(true, null);
    this.setColour('#0288D1');
    this.setTooltip("A numeric value");
    this.setHelpUrl("");
  }
};

// STRING block
Blockly.Blocks['STRING'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("String");
    this.setOutput(true, null);
    this.setColour('#0288D1');
    this.setTooltip("A text value");
    this.setHelpUrl("");
  }
};

// BOOLEAN block
Blockly.Blocks['BOOLEAN'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Boolean");
    this.setOutput(true, null);
    this.setColour('#0288D1');
    this.setTooltip("A true/false value");
    this.setHelpUrl("");
  }
};

// SET_VARIABLE block
Blockly.Blocks['SET_VARIABLE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set Variable");
    this.appendDummyInput().appendField("Variable:").appendField(new Blockly.FieldTextInput(""), "VARIABLE");
    this.appendDummyInput().appendField("Value:").appendField(new Blockly.FieldTextInput(""), "VALUE");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#0288D1');
    this.setTooltip("Sets the value of a variable");
    this.setHelpUrl("");
  }
};

// GET_VARIABLE block
Blockly.Blocks['GET_VARIABLE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get Variable");
    this.appendDummyInput().appendField("Variable_Name:").appendField(new Blockly.FieldTextInput(""), "VARIABLE_NAME");
    this.setOutput(true, null);
    this.setColour('#0288D1');
    this.setTooltip("Gets the value of a variable");
    this.setHelpUrl("");
  }
};

// SPAWN_VEHICLE block
Blockly.Blocks['SPAWN_VEHICLE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Spawn Vehicle");
    this.appendDummyInput().appendField("Vehicle_Type:").appendField(new Blockly.FieldTextInput(""), "VEHICLE_TYPE");
    this.appendDummyInput().appendField("Location:").appendField(new Blockly.FieldTextInput(""), "LOCATION");
    this.appendDummyInput().appendField("Team:").appendField(new Blockly.FieldTextInput(""), "TEAM");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#E64A19');
    this.setTooltip("Spawns a vehicle at a location");
    this.setHelpUrl("");
  }
};

// DESPAWN_VEHICLE block
Blockly.Blocks['DESPAWN_VEHICLE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Despawn Vehicle");
    this.appendDummyInput().appendField("Vehicle:").appendField(new Blockly.FieldTextInput(""), "VEHICLE");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#E64A19');
    this.setTooltip("Removes a vehicle from the game");
    this.setHelpUrl("");
  }
};

// VEHICLE_TYPE_TANK block
Blockly.Blocks['VEHICLE_TYPE_TANK'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Tank");
    this.setOutput(true, null);
    this.setColour('#E64A19');
    this.setTooltip("Tank vehicle type");
    this.setHelpUrl("");
  }
};

// VEHICLE_TYPE_APC block
Blockly.Blocks['VEHICLE_TYPE_APC'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("APC");
    this.setOutput(true, null);
    this.setColour('#E64A19');
    this.setTooltip("APC vehicle type");
    this.setHelpUrl("");
  }
};

// VEHICLE_TYPE_HELICOPTER block
Blockly.Blocks['VEHICLE_TYPE_HELICOPTER'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Helicopter");
    this.setOutput(true, null);
    this.setColour('#E64A19');
    this.setTooltip("Helicopter vehicle type");
    this.setHelpUrl("");
  }
};

// VEHICLE_TYPE_JET block
Blockly.Blocks['VEHICLE_TYPE_JET'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Jet");
    this.setOutput(true, null);
    this.setColour('#E64A19');
    this.setTooltip("Jet vehicle type");
    this.setHelpUrl("");
  }
};

// VEHICLE_TYPE_TRANSPORT block
Blockly.Blocks['VEHICLE_TYPE_TRANSPORT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Transport");
    this.setOutput(true, null);
    this.setColour('#E64A19');
    this.setTooltip("Transport vehicle type");
    this.setHelpUrl("");
  }
};

// GET_VEHICLE_HEALTH block
Blockly.Blocks['GET_VEHICLE_HEALTH'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get Vehicle Health");
    this.appendDummyInput().appendField("Vehicle:").appendField(new Blockly.FieldTextInput(""), "VEHICLE");
    this.setOutput(true, null);
    this.setColour('#E64A19');
    this.setTooltip("Returns the current health of a vehicle");
    this.setHelpUrl("");
  }
};

// SET_VEHICLE_HEALTH block
Blockly.Blocks['SET_VEHICLE_HEALTH'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set Vehicle Health");
    this.appendDummyInput().appendField("Vehicle:").appendField(new Blockly.FieldTextInput(""), "VEHICLE");
    this.appendDummyInput().appendField("Health:").appendField(new Blockly.FieldTextInput(""), "HEALTH");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#E64A19');
    this.setTooltip("Sets the health of a vehicle");
    this.setHelpUrl("");
  }
};

// GET_VEHICLE_DRIVER block
Blockly.Blocks['GET_VEHICLE_DRIVER'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get Vehicle Driver");
    this.appendDummyInput().appendField("Vehicle:").appendField(new Blockly.FieldTextInput(""), "VEHICLE");
    this.setOutput(true, null);
    this.setColour('#E64A19');
    this.setTooltip("Returns the player driving the vehicle");
    this.setHelpUrl("");
  }
};

// EJECT_FROM_VEHICLE block
Blockly.Blocks['EJECT_FROM_VEHICLE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Eject from Vehicle");
    this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Vehicle:").appendField(new Blockly.FieldTextInput(""), "VEHICLE");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#E64A19');
    this.setTooltip("Forces a player out of a vehicle");
    this.setHelpUrl("");
  }
};

// LOCK_VEHICLE block
Blockly.Blocks['LOCK_VEHICLE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Lock Vehicle");
    this.appendDummyInput().appendField("Vehicle:").appendField(new Blockly.FieldTextInput(""), "VEHICLE");
    this.appendDummyInput().appendField("Team:").appendField(new Blockly.FieldTextInput(""), "TEAM");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#E64A19');
    this.setTooltip("Locks a vehicle for a specific team");
    this.setHelpUrl("");
  }
};

// SET_VEHICLE_SPEED block
Blockly.Blocks['SET_VEHICLE_SPEED'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set Vehicle Speed");
    this.appendDummyInput().appendField("Vehicle:").appendField(new Blockly.FieldTextInput(""), "VEHICLE");
    this.appendDummyInput().appendField("Speed:").appendField(new Blockly.FieldTextInput(""), "SPEED");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#E64A19');
    this.setTooltip("Sets the speed of a vehicle");
    this.setHelpUrl("");
  }
};

// DISABLE_VEHICLE block
Blockly.Blocks['DISABLE_VEHICLE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Disable Vehicle");
    this.appendDummyInput().appendField("Vehicle:").appendField(new Blockly.FieldTextInput(""), "VEHICLE");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#E64A19');
    this.setTooltip("Disables vehicle movement and weapons");
    this.setHelpUrl("");
  }
};

// ENABLE_VEHICLE block
Blockly.Blocks['ENABLE_VEHICLE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Enable Vehicle");
    this.appendDummyInput().appendField("Vehicle:").appendField(new Blockly.FieldTextInput(""), "VEHICLE");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('#E64A19');
    this.setTooltip("Enables vehicle movement and weapons");
    this.setHelpUrl("");
  }
};
