// Autogenerated Blockly Block Definitions


Blockly.Blocks['MOD_BLOCK'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("MOD");
    // Serenity-style: container-only block (no editable text fields).
    // Holds Rule blocks and nothing else.

        this.setPreviousStatement(false, null);
    this.setNextStatement(false, null);
      // Keep the RULES statement input, but do not render an additional label.
      this.appendStatementInput("RULES").setCheck("Rule");
    this.setDeletable(false);
    this.setMovable(false);

    this.setColour('#4A4A4A');
    this.setTooltip("");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['RULE_HEADER'] = {
  init: function() {
    // Keep everything on the top row: <rule name>  Event <event> <scope>
    this.appendDummyInput()
        .appendField(new Blockly.FieldTextInput("New Rule"), "RULE_NAME")
        .appendField("Event")
        .appendField(new Blockly.FieldDropdown([
      ["Ongoing", "Ongoing"],
      ["OnAIMoveToFailed", "OnAIMoveToFailed"],
      ["OnAIMoveToRunning", "OnAIMoveToRunning"],
      ["OnAIMoveToSucceeded", "OnAIMoveToSucceeded"],
      ["OnAIParachuteRunning", "OnAIParachuteRunning"],
      ["OnAIParachuteSucceeded", "OnAIParachuteSucceeded"],
      ["OnAIWaypointIdleFailed", "OnAIWaypointIdleFailed"],
      ["OnAIWaypointIdleRunning", "OnAIWaypointIdleRunning"],
      ["OnAIWaypointIdleSucceeded", "OnAIWaypointIdleSucceeded"],
      ["OnCapturePointCaptured", "OnCapturePointCaptured"],
      ["OnCapturePointCapturing", "OnCapturePointCapturing"],
      ["OnCapturePointLost", "OnCapturePointLost"],
      ["OnGameModeEnding", "OnGameModeEnding"],
      ["OnGameModeStarted", "OnGameModeStarted"],
      ["OnMandown", "OnMandown"],
      ["OnMCOMArmed", "OnMCOMArmed"],
      ["OnMCOMDefused", "OnMCOMDefused"],
      ["OnMCOMDestroyed", "OnMCOMDestroyed"],
      ["OnPlayerDamaged", "OnPlayerDamaged"],
      ["OnPlayerDeployed", "OnPlayerDeployed"],
      ["OnPlayerDied", "OnPlayerDied"],
      ["OnPlayerEarnedKill", "OnPlayerEarnedKill"],
      ["OnPlayerEarnedKillAssist", "OnPlayerEarnedKillAssist"],
      ["OnPlayerEnterAreaTrigger", "OnPlayerEnterAreaTrigger"],
      ["OnPlayerEnterCapturePoint", "OnPlayerEnterCapturePoint"],
      ["OnPlayerEnterVehicle", "OnPlayerEnterVehicle"],
      ["OnPlayerEnterVehicleSeat", "OnPlayerEnterVehicleSeat"],
      ["OnPlayerExitAreaTrigger", "OnPlayerExitAreaTrigger"],
      ["OnPlayerExitCapturePoint", "OnPlayerExitCapturePoint"],
      ["OnPlayerExitVehicle", "OnPlayerExitVehicle"],
      ["OnPlayerExitVehicleSeat", "OnPlayerExitVehicleSeat"],
      ["OnPlayerInteract", "OnPlayerInteract"],
      ["OnPlayerJoinGame", "OnPlayerJoinGame"],
      ["OnPlayerLeaveGame", "OnPlayerLeaveGame"],
      ["OnPlayerSwitchTeam", "OnPlayerSwitchTeam"],
      ["OnPlayerUIButtonEvent", "OnPlayerUIButtonEvent"],
      ["OnPlayerUndeploy", "OnPlayerUndeploy"],
      ["OnRayCastHit", "OnRayCastHit"],
      ["OnRayCastMissed", "OnRayCastMissed"],
      ["OnRevived", "OnRevived"],
      ["OnRingOfFireZoneSizeChange", "OnRingOfFireZoneSizeChange"],
      ["OnSpawnerSpawned", "OnSpawnerSpawned"],
      ["OnTimeLimitReached", "OnTimeLimitReached"],
      ["OnVehicleDestroyed", "OnVehicleDestroyed"],
      ["OnVehicleSpawned", "OnVehicleSpawned"],
    ]), "EVENT_TYPE")

    // Official UI: this dropdown is present but not labeled (starts with Global).
        .appendField(new Blockly.FieldDropdown([
      ["Global", "Global"],
      ["AreaTrigger", "AreaTrigger"],
      ["CapturePoint", "CapturePoint"],
      ["EmplacementSpawner", "EmplacementSpawner"],
      ["HQ", "HQ"],
      ["InteractPoint", "InteractPoint"],
      ["LootSpawner", "LootSpawner"],
      ["MCOM", "MCOM"],
      ["Player", "Player"],
      ["RingOfFire", "RingOfFire"],
      ["ScreenEffect [depreciated]", "ScreenEffect [depreciated]"],
      ["Sector", "Sector"],
      ["SFX", "SFX"],
      ["SpatialObject", "SpatialObject"],
      ["spawner", "spawner"],
      ["spawnPoint", "spawnPoint"],
      ["Team", "Team"],
      ["Vehicle", "Vehicle"],
      ["VehicleSpawner", "VehicleSpawner"],
      ["VFX", "VFX"],
      ["VO", "VO"],
      ["WaypointPath", "WaypointPath"],
      ["WorldIcon", "WorldIcon"],
    ]), "SCOPE");

        this.setPreviousStatement(true, "Rule");
    this.setNextStatement(true, "Rule");
    this.appendStatementInput("CONDITIONS").setCheck("Condition").appendField("Conditions:");
    this.appendStatementInput("ACTIONS").setCheck(["Action", "SubroutineReference", "ControlAction"]).appendField("Actions:");

    this.setColour('#A285E6');
    this.setTooltip("");
    this.setHelpUrl("");
  }
};

// Placeholder "Condition" block

Blockly.Blocks['CONDITION_BLOCK'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Condition");
    
        this.setPreviousStatement(true, "Condition");
    this.setNextStatement(true, "Condition");

    this.setColour('#45B5B5');
    this.setTooltip("A placeholder condition block.");
    this.setHelpUrl("");
  }
};

// Placeholder "Action" block

Blockly.Blocks['ACTION_BLOCK'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Action");
    
        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#B5A045');
    this.setTooltip("A placeholder action block.");
    this.setHelpUrl("");
  }
};

// Placeholder "SUBROUTINE:" block

Blockly.Blocks['SUBROUTINE_BLOCK'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("SUBROUTINE:");
    
        this.setPreviousStatement(false, null);
    this.setNextStatement(false, null);
    this.appendStatementInput("ACTIONS_CONDITIONS").setCheck(["Action", "Condition"]).appendField("Logic:");

    this.setColour('#E6A85C');
    this.setTooltip("Reusable logic blocks that can be called from multiple places.");
    this.setHelpUrl("");
  }
};

// Placeholder "Call Subroutine:" block

Blockly.Blocks['SUBROUTINE_REFERENCE_BLOCK'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Call Subroutine:");
    
        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#E6A85C');
    this.setTooltip("Calls a defined subroutine.");
    this.setHelpUrl("");
  }
};

// Placeholder "Control Action:" block

Blockly.Blocks['CONTROL_ACTION_BLOCK'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Control Action:");
    
        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#A285E6');
    this.setTooltip("A placeholder control action block.");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['AIBATTLEFIELDBEHAVIOUR'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("AIBattlefieldBehaviour");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#B5A045');
    this.setTooltip("");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['AIDEFENDPOSITIONBEHAVIOUR'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("AIDefendPositionBehaviour");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#B5A045');
    this.setTooltip("");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['AIIDLEBEHAVIOUR'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("AIIdleBehaviour");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#B5A045');
    this.setTooltip("");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['AILOSMOVETOBEHAVIOUR'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("AILOSMoveTOBehaviour");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#B5A045');
    this.setTooltip("");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['AIMOVETOBEHAVIOUR'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("AIMoveToBehaviour");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#B5A045');
    this.setTooltip("");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['AIPARACHUTEBEHAVIOUR'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("AIParachuteBehaviour");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#B5A045');
    this.setTooltip("");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['AIVALIDATEMOVETOBEHAVIOUR'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("AIValidateMoveToBehaviour");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#B5A045');
    this.setTooltip("");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['AIWAYPOINTIDLEBEHAVIOUR'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("AIWaypointIdleBehaviour");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#B5A045');
    this.setTooltip("");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['SETPLAYERHEALTH'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set Player Health");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Health:").appendField(new Blockly.FieldTextInput(""), "HEALTH");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#C2185B');
    this.setTooltip("Sets the health of a player.");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['SETPLAYERLOADOUT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("SetPlayerLoadout");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Loadout:").appendField(new Blockly.FieldTextInput(""), "LOADOUT");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#B5A045');
    this.setTooltip("");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['TELEPORT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Teleport");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Location:").appendField(new Blockly.FieldTextInput(""), "LOCATION");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#B5A045');
    this.setTooltip("");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['ENDROUND'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("End Round");
        this.appendDummyInput().appendField("Winning Team:").appendField(new Blockly.FieldTextInput(""), "WINNING_TEAM");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#5D4037');
    this.setTooltip("Ends the round, declaring a winning team.");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['PAUSEROUND'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("PauseRound");
    
        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#B5A045');
    this.setTooltip("");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['AIBATTLEFIELDBEHAVIOR'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("AI Battlefield Behavior");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#D32F2F');
    this.setTooltip("Sets the AI to standard battlefield combat behavior");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['AIDEFENDPOSITIONBEHAVIOR'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("AI Defend Position Behavior");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Position:").appendField(new Blockly.FieldTextInput(""), "POSITION");
    this.appendDummyInput().appendField("Radius:").appendField(new Blockly.FieldTextInput(""), "RADIUS");
    this.appendDummyInput().appendField("Time:").appendField(new Blockly.FieldTextInput(""), "TIME");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#D32F2F');
    this.setTooltip("Orders AI to defend a specific area");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['AIIDLEBEHAVIOR'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("AI Idle Behavior");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#D32F2F');
    this.setTooltip("Sets the AI to idle state");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['AIMOVETOBEHAVIOR'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("AI Move To Behavior");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Position:").appendField(new Blockly.FieldTextInput(""), "POSITION");
    this.appendDummyInput().appendField("Sprint:").appendField(new Blockly.FieldTextInput(""), "SPRINT");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#D32F2F');
    this.setTooltip("Orders AI to move to a location");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['AIPARACHUTEBEHAVIOR'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("AI Parachute Behavior");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#D32F2F');
    this.setTooltip("Orders AI to deploy parachute");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['AIWAYPOINTIDLEBEHAVIOR'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("AI Waypoint Idle Behavior");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Time:").appendField(new Blockly.FieldTextInput(""), "TIME");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#D32F2F');
    this.setTooltip("AI waits at a waypoint for a duration");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['AIFOLLOWPLAYER'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("AI Follow Player");
        this.appendDummyInput().appendField("Ai Player:").appendField(new Blockly.FieldTextInput(""), "AI_PLAYER");
    this.appendDummyInput().appendField("Target Player:").appendField(new Blockly.FieldTextInput(""), "TARGET_PLAYER");
    this.appendDummyInput().appendField("Distance:").appendField(new Blockly.FieldTextInput(""), "DISTANCE");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#D32F2F');
    this.setTooltip("Orders AI to follow a specific player");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['AIHOLDPOSITION'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("AI Hold Position");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#D32F2F');
    this.setTooltip("Orders AI to hold their current position");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['AIATTACKTARGET'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("AI Attack Target");
        this.appendDummyInput().appendField("Ai Player:").appendField(new Blockly.FieldTextInput(""), "AI_PLAYER");
    this.appendDummyInput().appendField("Target Player:").appendField(new Blockly.FieldTextInput(""), "TARGET_PLAYER");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#D32F2F');
    this.setTooltip("Orders AI to attack a specific target");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['SETAIBEHAVIOR'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set AI Behavior");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Behavior Mode:").appendField(new Blockly.FieldTextInput(""), "BEHAVIOR_MODE");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#D32F2F');
    this.setTooltip("Sets the general behavior mode for the AI");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['DEPLOYAI'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Deploy AI");
        this.appendDummyInput().appendField("Team:").appendField(new Blockly.FieldTextInput(""), "TEAM");
    this.appendDummyInput().appendField("Soldier Type:").appendField(new Blockly.FieldTextInput(""), "SOLDIER_TYPE");
    this.appendDummyInput().appendField("Position:").appendField(new Blockly.FieldTextInput(""), "POSITION");
    this.appendDummyInput().appendField("Kit:").appendField(new Blockly.FieldTextInput(""), "KIT");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#D32F2F');
    this.setTooltip("Spawns a new AI soldier");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['DESPAWNAI'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Despawn AI");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#D32F2F');
    this.setTooltip("Removes an AI soldier from the game");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['SETAISPAWNLOCATION'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set AI Spawn Location");
        this.appendDummyInput().appendField("Team:").appendField(new Blockly.FieldTextInput(""), "TEAM");
    this.appendDummyInput().appendField("Position:").appendField(new Blockly.FieldTextInput(""), "POSITION");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#D32F2F');
    this.setTooltip("Sets where AI soldiers will spawn");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['SETAIHEALTH'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set AI Health");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Amount:").appendField(new Blockly.FieldTextInput(""), "AMOUNT");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#D32F2F');
    this.setTooltip("Sets the health of an AI soldier");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['SETAITEAM'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set AI Team");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Team Id:").appendField(new Blockly.FieldTextInput(""), "TEAM_ID");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#D32F2F');
    this.setTooltip("Changes the team of an AI soldier");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['GETAIHEALTH'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get AI Health");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");

        this.setOutput(true, null);

    this.setColour('#D32F2F');
    this.setTooltip("Returns the current health of an AI soldier");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['GETAITEAM'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get AI Team");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");

        this.setOutput(true, null);

    this.setColour('#D32F2F');
    this.setTooltip("Returns the team ID of an AI soldier");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['AIISALIVE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("AI Is Alive");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");

        this.setPreviousStatement(true, "Condition");
    this.setNextStatement(true, "Condition");

    this.setColour('#D32F2F');
    this.setTooltip("Checks if an AI soldier is currently alive");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['CREATEARRAY'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Create Array");
    
        this.setOutput(true, null);

    this.setColour('#0097A7');
    this.setTooltip("Creates an empty array.");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['ARRAYLENGTH'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Array Length");
        this.appendDummyInput().appendField("Array:").appendField(new Blockly.FieldTextInput(""), "ARRAY");

        this.setOutput(true, null);

    this.setColour('#0097A7');
    this.setTooltip("Returns the number of elements in an array.");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['GETELEMENT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get Element");
        this.appendDummyInput().appendField("Array:").appendField(new Blockly.FieldTextInput(""), "ARRAY");
    this.appendDummyInput().appendField("Index:").appendField(new Blockly.FieldTextInput(""), "INDEX");

        this.setOutput(true, null);

    this.setColour('#0097A7');
    this.setTooltip("Returns the element at a specific index in an array.");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['SETELEMENT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set Element");
        this.appendDummyInput().appendField("Array:").appendField(new Blockly.FieldTextInput(""), "ARRAY");
    this.appendDummyInput().appendField("Index:").appendField(new Blockly.FieldTextInput(""), "INDEX");
    this.appendDummyInput().appendField("Value:").appendField(new Blockly.FieldTextInput(""), "VALUE");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#0097A7');
    this.setTooltip("Sets the element at a specific index in an array.");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['APPENDTOARRAY'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Append To Array");
        this.appendDummyInput().appendField("Array:").appendField(new Blockly.FieldTextInput(""), "ARRAY");
    this.appendDummyInput().appendField("Value:").appendField(new Blockly.FieldTextInput(""), "VALUE");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#0097A7');
    this.setTooltip("Adds a value to the end of an array.");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['REMOVEFROMARRAY'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Remove From Array");
        this.appendDummyInput().appendField("Array:").appendField(new Blockly.FieldTextInput(""), "ARRAY");
    this.appendDummyInput().appendField("Index:").appendField(new Blockly.FieldTextInput(""), "INDEX");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#0097A7');
    this.setTooltip("Removes an element from an array at a specific index.");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['FINDFIRST'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Find First");
        this.appendDummyInput().appendField("Array:").appendField(new Blockly.FieldTextInput(""), "ARRAY");
    this.appendDummyInput().appendField("Value:").appendField(new Blockly.FieldTextInput(""), "VALUE");

        this.setOutput(true, null);

    this.setColour('#0097A7');
    this.setTooltip("Finds the first index of a value in an array. Returns -1 if not found.");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['SORTARRAY'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Sort Array");
        this.appendDummyInput().appendField("Array:").appendField(new Blockly.FieldTextInput(""), "ARRAY");
    this.appendDummyInput().appendField("Order:").appendField(new Blockly.FieldTextInput(""), "ORDER");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#0097A7');
    this.setTooltip("Sorts an array in ascending or descending order.");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['LOADMUSIC'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("LoadMusic");
        this.appendDummyInput().appendField("Music Id:").appendField(new Blockly.FieldTextInput(""), "MUSIC_ID");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#455A64');
    this.setTooltip("");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['PLAYMUSIC'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("PlayMusic");
        this.appendDummyInput().appendField("Music Id:").appendField(new Blockly.FieldTextInput(""), "MUSIC_ID");
    this.appendDummyInput().appendField("Players:").appendField(new Blockly.FieldTextInput(""), "PLAYERS");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#455A64');
    this.setTooltip("");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['SETMUSICPARAM'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("SetMusicParam");
        this.appendDummyInput().appendField("Music Id:").appendField(new Blockly.FieldTextInput(""), "MUSIC_ID");
    this.appendDummyInput().appendField("Param:").appendField(new Blockly.FieldTextInput(""), "PARAM");
    this.appendDummyInput().appendField("Players:").appendField(new Blockly.FieldTextInput(""), "PLAYERS");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#455A64');
    this.setTooltip("");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['UNLOADMUSIC'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("UnloadMusic");
        this.appendDummyInput().appendField("Music Id:").appendField(new Blockly.FieldTextInput(""), "MUSIC_ID");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#455A64');
    this.setTooltip("");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['PLAYSOUND'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("PlaySound");
        this.appendDummyInput().appendField("Sound Id:").appendField(new Blockly.FieldTextInput(""), "SOUND_ID");
    this.appendDummyInput().appendField("Position:").appendField(new Blockly.FieldTextInput(""), "POSITION");
    this.appendDummyInput().appendField("Players:").appendField(new Blockly.FieldTextInput(""), "PLAYERS");
    this.appendDummyInput().appendField("Volume:").appendField(new Blockly.FieldTextInput(""), "VOLUME");
    this.appendDummyInput().appendField("Pitch:").appendField(new Blockly.FieldTextInput(""), "PITCH");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#455A64');
    this.setTooltip("");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['PLAYVO'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("PlayVO");
        this.appendDummyInput().appendField("Vo Id:").appendField(new Blockly.FieldTextInput(""), "VO_ID");
    this.appendDummyInput().appendField("Speaker:").appendField(new Blockly.FieldTextInput(""), "SPEAKER");
    this.appendDummyInput().appendField("Listener:").appendField(new Blockly.FieldTextInput(""), "LISTENER");
    this.appendDummyInput().appendField("Players:").appendField(new Blockly.FieldTextInput(""), "PLAYERS");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#455A64');
    this.setTooltip("");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['STOPSOUND'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("StopSound");
        this.appendDummyInput().appendField("Sound Id:").appendField(new Blockly.FieldTextInput(""), "SOUND_ID");
    this.appendDummyInput().appendField("Players:").appendField(new Blockly.FieldTextInput(""), "PLAYERS");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#455A64');
    this.setTooltip("");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['SETPLAYERCAMERA'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set Player Camera");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Camera Mode:").appendField(new Blockly.FieldTextInput(""), "CAMERA_MODE");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#37474F');
    this.setTooltip("Sets the camera mode for a specific player");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['LOCKCAMERATOTARGET'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Lock Camera to Target");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Target:").appendField(new Blockly.FieldTextInput(""), "TARGET");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#37474F');
    this.setTooltip("Locks the player's camera to look at a target");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['CAMERASHAKE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Camera Shake");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Intensity:").appendField(new Blockly.FieldTextInput(""), "INTENSITY");
    this.appendDummyInput().appendField("Duration:").appendField(new Blockly.FieldTextInput(""), "DURATION");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#37474F');
    this.setTooltip("Applies a shake effect to the player's camera");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['SETCAMERAFOV'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set Camera FOV");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Fov:").appendField(new Blockly.FieldTextInput(""), "FOV");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#37474F');
    this.setTooltip("Sets the Field of View for the player's camera");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['RESETCAMERA'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Reset Camera");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#37474F');
    this.setTooltip("Resets the player's camera to default");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['FIRSTPERSONCAMERA'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("First Person Camera");
    
        this.setOutput(true, null);

    this.setColour('#37474F');
    this.setTooltip("First person camera mode");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['THIRDPERSONCAMERA'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Third Person Camera");
    
        this.setOutput(true, null);

    this.setColour('#37474F');
    this.setTooltip("Third person camera mode");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['FREECAMERA'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Free Camera");
    
        this.setOutput(true, null);

    this.setColour('#37474F');
    this.setTooltip("Free camera mode");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['SPECTATORCAMERA'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Spectator Camera");
    
        this.setOutput(true, null);

    this.setColour('#37474F');
    this.setTooltip("Spectator camera mode");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['EQUAL'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Equal");
        this.appendDummyInput().appendField("A:").appendField(new Blockly.FieldTextInput(""), "A");
    this.appendDummyInput().appendField("B:").appendField(new Blockly.FieldTextInput(""), "B");

        this.setOutput(true, null);

    this.setColour('#1976D2');
    this.setTooltip("Returns True if inputs are equal");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['NOTEQUAL'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Not Equal");
        this.appendDummyInput().appendField("A:").appendField(new Blockly.FieldTextInput(""), "A");
    this.appendDummyInput().appendField("B:").appendField(new Blockly.FieldTextInput(""), "B");

        this.setOutput(true, null);

    this.setColour('#1976D2');
    this.setTooltip("Returns True if inputs are not equal");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['LESSTHAN'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Less Than");
        this.appendDummyInput().appendField("A:").appendField(new Blockly.FieldTextInput(""), "A");
    this.appendDummyInput().appendField("B:").appendField(new Blockly.FieldTextInput(""), "B");

        this.setOutput(true, null);

    this.setColour('#1976D2');
    this.setTooltip("Returns True if A < B");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['LESSTHANOREQUAL'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Less Than Or Equal");
        this.appendDummyInput().appendField("Value A:").appendField(new Blockly.FieldTextInput(""), "VALUE_A");
    this.appendDummyInput().appendField("Value B:").appendField(new Blockly.FieldTextInput(""), "VALUE_B");

        this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);

    this.setColour('#45B5B5');
    this.setTooltip("Returns true if A is less than or equal to B");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['GREATERTHAN'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Greater Than");
        this.appendDummyInput().appendField("A:").appendField(new Blockly.FieldTextInput(""), "A");
    this.appendDummyInput().appendField("B:").appendField(new Blockly.FieldTextInput(""), "B");

        this.setOutput(true, null);

    this.setColour('#1976D2');
    this.setTooltip("Returns True if A > B");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['GREATERTHANOREQUAL'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Greater Than Or Equal");
        this.appendDummyInput().appendField("Value A:").appendField(new Blockly.FieldTextInput(""), "VALUE_A");
    this.appendDummyInput().appendField("Value B:").appendField(new Blockly.FieldTextInput(""), "VALUE_B");

        this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);

    this.setColour('#45B5B5');
    this.setTooltip("Returns true if A is greater than or equal to B");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['PLAYEFFECT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Play Effect");
        this.appendDummyInput().appendField("Effect Type:").appendField(new Blockly.FieldTextInput(""), "EFFECT_TYPE");
    this.appendDummyInput().appendField("Location:").appendField(new Blockly.FieldTextInput(""), "LOCATION");
    this.appendDummyInput().appendField("Scale:").appendField(new Blockly.FieldTextInput(""), "SCALE");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#263238');
    this.setTooltip("Plays a visual effect at a location");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['STOPEFFECT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Stop Effect");
        this.appendDummyInput().appendField("Effect Id:").appendField(new Blockly.FieldTextInput(""), "EFFECT_ID");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#263238');
    this.setTooltip("Stops a playing effect");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['PARTICLEEFFECT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Particle Effect");
        this.appendDummyInput().appendField("Particle Type:").appendField(new Blockly.FieldTextInput(""), "PARTICLE_TYPE");

        this.setOutput(true, null);

    this.setColour('#263238');
    this.setTooltip("Returns a particle effect type");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['EXPLOSIONEFFECT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Explosion Effect");
        this.appendDummyInput().appendField("Explosion Type:").appendField(new Blockly.FieldTextInput(""), "EXPLOSION_TYPE");

        this.setOutput(true, null);

    this.setColour('#263238');
    this.setTooltip("Returns an explosion effect type");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['SCREENFLASH'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Screen Flash");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Color:").appendField(new Blockly.FieldTextInput(""), "COLOR");
    this.appendDummyInput().appendField("Duration:").appendField(new Blockly.FieldTextInput(""), "DURATION");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#263238');
    this.setTooltip("Flashes the player's screen with a color");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['SCREENFADE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Screen Fade");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Fade Type:").appendField(new Blockly.FieldTextInput(""), "FADE_TYPE");
    this.appendDummyInput().appendField("Duration:").appendField(new Blockly.FieldTextInput(""), "DURATION");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#263238');
    this.setTooltip("Fades the player's screen");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['APPLYSCREENFILTER'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Apply Screen Filter");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Filter Type:").appendField(new Blockly.FieldTextInput(""), "FILTER_TYPE");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#263238');
    this.setTooltip("Applies a visual filter to the player's screen");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['DEPLOYEMPLACEMENT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("DeployEmplacement");
        this.appendDummyInput().appendField("Emplacement Id:").appendField(new Blockly.FieldTextInput(""), "EMPLACEMENT_ID");
    this.appendDummyInput().appendField("Position:").appendField(new Blockly.FieldTextInput(""), "POSITION");
    this.appendDummyInput().appendField("Rotation:").appendField(new Blockly.FieldTextInput(""), "ROTATION");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#8D6E63');
    this.setTooltip("");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['ON_START'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("On Game Start");
    
        this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);

    this.setColour('#5D4037');
    this.setTooltip("");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['ON_PLAYER_JOIN'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("On Player Join");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");

        this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);

    this.setColour('#5D4037');
    this.setTooltip("");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['EVENTATTACKER'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Event Attacker");
    
        this.setOutput(true, null);

    this.setColour('#5D4037');
    this.setTooltip("The player who caused the event (e.g. the killer)");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['EVENTDAMAGE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Event Damage");
    
        this.setOutput(true, null);

    this.setColour('#5D4037');
    this.setTooltip("The amount of damage dealt in the event");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['EVENTLOCATION'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Event Location");
    
        this.setOutput(true, null);

    this.setColour('#5D4037');
    this.setTooltip("The location where the event occurred");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['EVENTPLAYER'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Event Player");
    
        this.setOutput(true, null);

    this.setColour('#5D4037');
    this.setTooltip("The primary player involved in the event");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['EVENTTEAM'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Event Team");
    
        this.setOutput(true, null);

    this.setColour('#5D4037');
    this.setTooltip("The team involved in the event");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['EVENTVICTIM'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Event Victim");
    
        this.setOutput(true, null);

    this.setColour('#5D4037');
    this.setTooltip("The player who was the victim of the event");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['EVENTWEAPON'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Event Weapon");
    
        this.setOutput(true, null);

    this.setColour('#5D4037');
    this.setTooltip("The weapon used in the event");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['GETGAMEMODE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get Gamemode");
    
        this.setOutput(true, null);

    this.setColour('#5D4037');
    this.setTooltip("Gets the current gamemode.");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['SETGAMEMODE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set Gamemode");
        this.appendDummyInput().appendField("Gamemode:").appendField(new Blockly.FieldTextInput(""), "GAMEMODE");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#5D4037');
    this.setTooltip("Sets the current gamemode.");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['ENABLEFRIENDLYFIRE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Enable Friendly Fire");
        this.appendDummyInput().appendField("Enabled:").appendField(new Blockly.FieldTextInput(""), "ENABLED");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#5D4037');
    this.setTooltip("Enables or disables friendly fire.");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['SETSCORE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set Score");
        this.appendDummyInput().appendField("Team:").appendField(new Blockly.FieldTextInput(""), "TEAM");
    this.appendDummyInput().appendField("Score:").appendField(new Blockly.FieldTextInput(""), "SCORE");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#5D4037');
    this.setTooltip("Sets the score for a team.");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['GETSCORE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get Score");
        this.appendDummyInput().appendField("Team:").appendField(new Blockly.FieldTextInput(""), "TEAM");

        this.setOutput(true, null);

    this.setColour('#5D4037');
    this.setTooltip("Gets the score for a team.");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['SETTIMELIMIT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set Time Limit");
        this.appendDummyInput().appendField("Time Limit:").appendField(new Blockly.FieldTextInput(""), "TIME_LIMIT");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#5D4037');
    this.setTooltip("Sets the time limit for the round.");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['GETTIMELIMIT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get Time Limit");
    
        this.setOutput(true, null);

    this.setColour('#5D4037');
    this.setTooltip("Gets the time limit for the round.");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['WAIT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Wait");
        this.appendDummyInput().appendField("Seconds:").appendField(new Blockly.FieldTextInput(""), "SECONDS");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#1976D2');
    this.setTooltip("Pauses execution for a specified time");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['WAITUNTIL'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Wait Until");
        this.appendDummyInput().appendField("Condition:").appendField(new Blockly.FieldTextInput(""), "CONDITION");
    this.appendDummyInput().appendField("Timeout:").appendField(new Blockly.FieldTextInput(""), "TIMEOUT");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#1976D2');
    this.setTooltip("Pauses execution until condition is true");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['BREAK'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Break");
    
        this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);

    this.setColour('#1976D2');
    this.setTooltip("Exits the current loop immediately");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['CONTINUE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Continue");
    
        this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);

    this.setColour('#1976D2');
    this.setTooltip("Skips to the next iteration of the current loop");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['IF'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("If");
        this.appendDummyInput().appendField("Condition:").appendField(new Blockly.FieldTextInput(""), "CONDITION");

        this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);

    this.setColour('#1976D2');
    this.setTooltip("Executes nested blocks if condition is true");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['WHILE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("While");
        this.appendDummyInput().appendField("Condition:").appendField(new Blockly.FieldTextInput(""), "CONDITION");

        this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);

    this.setColour('#1976D2');
    this.setTooltip("Repeats nested blocks while condition is true");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['AND'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("And");
        this.appendDummyInput().appendField("A:").appendField(new Blockly.FieldTextInput(""), "A");
    this.appendDummyInput().appendField("B:").appendField(new Blockly.FieldTextInput(""), "B");

        this.setOutput(true, null);

    this.setColour('#1976D2');
    this.setTooltip("Returns True if both inputs are True");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['OR'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Or");
        this.appendDummyInput().appendField("A:").appendField(new Blockly.FieldTextInput(""), "A");
    this.appendDummyInput().appendField("B:").appendField(new Blockly.FieldTextInput(""), "B");

        this.setOutput(true, null);

    this.setColour('#1976D2');
    this.setTooltip("Returns True if either input is True");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['NOT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Not");
        this.appendDummyInput().appendField("A:").appendField(new Blockly.FieldTextInput(""), "A");

        this.setOutput(true, null);

    this.setColour('#1976D2');
    this.setTooltip("Returns the opposite boolean value");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['TRUE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("True");
    
        this.setOutput(true, null);

    this.setColour('#1976D2');
    this.setTooltip("Boolean True value");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['FALSE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("False");
    
        this.setOutput(true, null);

    this.setColour('#1976D2');
    this.setTooltip("Boolean False value");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['GREATERTHANEQUAL'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Greater Than Or Equal");
        this.appendDummyInput().appendField("A:").appendField(new Blockly.FieldTextInput(""), "A");
    this.appendDummyInput().appendField("B:").appendField(new Blockly.FieldTextInput(""), "B");

        this.setOutput(true, null);

    this.setColour('#1976D2');
    this.setTooltip("Returns True if A >= B");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['LESSTHANEQUAL'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Less Than Or Equal");
        this.appendDummyInput().appendField("A:").appendField(new Blockly.FieldTextInput(""), "A");
    this.appendDummyInput().appendField("B:").appendField(new Blockly.FieldTextInput(""), "B");

        this.setOutput(true, null);

    this.setColour('#1976D2');
    this.setTooltip("Returns True if A <= B");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['FORVARIABLE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("ForVariable");
        this.appendDummyInput().appendField("From Value:").appendField(new Blockly.FieldTextInput(""), "FROM_VALUE");
    this.appendDummyInput().appendField("To Value:").appendField(new Blockly.FieldTextInput(""), "TO_VALUE");
    this.appendDummyInput().appendField("By Value:").appendField(new Blockly.FieldTextInput(""), "BY_VALUE");

        this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);

    this.setColour('#1976D2');
    this.setTooltip("Loops from starting value to ending value by increment");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['ADD'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Add");
        this.appendDummyInput().appendField("Value A:").appendField(new Blockly.FieldTextInput(""), "VALUE_A");
    this.appendDummyInput().appendField("Value B:").appendField(new Blockly.FieldTextInput(""), "VALUE_B");

        this.setOutput(true, null);

    this.setColour('#1976D2');
    this.setTooltip("Returns the sum of A and B");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['SUBTRACT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Subtract");
        this.appendDummyInput().appendField("Value A:").appendField(new Blockly.FieldTextInput(""), "VALUE_A");
    this.appendDummyInput().appendField("Value B:").appendField(new Blockly.FieldTextInput(""), "VALUE_B");

        this.setOutput(true, null);

    this.setColour('#1976D2');
    this.setTooltip("Returns the difference of A and B");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['MULTIPLY'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Multiply");
        this.appendDummyInput().appendField("Value A:").appendField(new Blockly.FieldTextInput(""), "VALUE_A");
    this.appendDummyInput().appendField("Value B:").appendField(new Blockly.FieldTextInput(""), "VALUE_B");

        this.setOutput(true, null);

    this.setColour('#1976D2');
    this.setTooltip("Returns the product of A and B");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['DIVIDE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Divide");
        this.appendDummyInput().appendField("Value A:").appendField(new Blockly.FieldTextInput(""), "VALUE_A");
    this.appendDummyInput().appendField("Value B:").appendField(new Blockly.FieldTextInput(""), "VALUE_B");

        this.setOutput(true, null);

    this.setColour('#1976D2');
    this.setTooltip("Returns the quotient of A and B");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['POWER'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Power");
        this.appendDummyInput().appendField("Base:").appendField(new Blockly.FieldTextInput(""), "BASE");
    this.appendDummyInput().appendField("Exponent:").appendField(new Blockly.FieldTextInput(""), "EXPONENT");

        this.setOutput(true, null);

    this.setColour('#1976D2');
    this.setTooltip("Returns the base to the exponent power.");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['SQUAREROOT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Square Root");
        this.appendDummyInput().appendField("Value:").appendField(new Blockly.FieldTextInput(""), "VALUE");

        this.setOutput(true, null);

    this.setColour('#1976D2');
    this.setTooltip("Returns the square root of a number.");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['ABSOLUTE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Absolute");
        this.appendDummyInput().appendField("Value:").appendField(new Blockly.FieldTextInput(""), "VALUE");

        this.setOutput(true, null);

    this.setColour('#1976D2');
    this.setTooltip("Returns the absolute value of a number.");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['MODULO'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Modulo");
        this.appendDummyInput().appendField("Dividend:").appendField(new Blockly.FieldTextInput(""), "DIVIDEND");
    this.appendDummyInput().appendField("Divisor:").appendField(new Blockly.FieldTextInput(""), "DIVISOR");

        this.setOutput(true, null);

    this.setColour('#1976D2');
    this.setTooltip("Returns the remainder of a division.");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['SETOBJECTIVESTATE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("SetObjectiveState");
        this.appendDummyInput().appendField("Objective:").appendField(new Blockly.FieldTextInput(""), "OBJECTIVE");
    this.appendDummyInput().appendField("State:").appendField(new Blockly.FieldTextInput(""), "STATE");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#F9A825');
    this.setTooltip("");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['GETOBJECTIVESTATE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("GetObjectiveState");
        this.appendDummyInput().appendField("Objective:").appendField(new Blockly.FieldTextInput(""), "OBJECTIVE");

        this.setOutput(true, null);

    this.setColour('#F9A825');
    this.setTooltip("");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['COMMENT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Comment");
        this.appendDummyInput().appendField("Text:").appendField(new Blockly.FieldTextInput(""), "TEXT");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#9E9E9E');
    this.setTooltip("");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['GETPLAYERBYID'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get Player By Id");
        this.appendDummyInput().appendField("Player Id:").appendField(new Blockly.FieldTextInput(""), "PLAYER_ID");

        this.setOutput(true, null);

    this.setColour('#C2185B');
    this.setTooltip("Gets a player by their ID.");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['GETPLAYERNAME'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get Player Name");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");

        this.setOutput(true, null);

    this.setColour('#C2185B');
    this.setTooltip("Gets the name of a player.");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['GETPLAYERHEALTH'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get Player Health");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");

        this.setOutput(true, null);

    this.setColour('#C2185B');
    this.setTooltip("Gets the health of a player.");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['TELEPORTPLAYER'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Teleport Player");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Position:").appendField(new Blockly.FieldTextInput(""), "POSITION");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#C2185B');
    this.setTooltip("Teleports a player to a specific location.");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['KILLPLAYER'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Kill Player");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#C2185B');
    this.setTooltip("Kills a player.");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['GETPLAYERTEAM'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get Player Team");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");

        this.setOutput(true, null);

    this.setColour('#C2185B');
    this.setTooltip("Gets the team of a player.");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['SETPLAYERTEAM'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set Player Team");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Team:").appendField(new Blockly.FieldTextInput(""), "TEAM");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#C2185B');
    this.setTooltip("Sets the team of a player.");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['CALLSUBROUTINE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Call Subroutine");
        this.appendDummyInput().appendField("Subroutine Name:").appendField(new Blockly.FieldDropdown([["NewSubroutine", "NEWSUBROUTINE"]]), "SUBROUTINE_NAME");

        this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);

    this.setColour('#E6A85C');
    this.setTooltip("Executes a subroutine");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['RETURN'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Return");
    
        this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);

    this.setColour('#E6A85C');
    this.setTooltip("Returns from the current subroutine");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['VECTOR'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Vector");
        this.appendDummyInput().appendField("X:").appendField(new Blockly.FieldTextInput(""), "X");
    this.appendDummyInput().appendField("Y:").appendField(new Blockly.FieldTextInput(""), "Y");
    this.appendDummyInput().appendField("Z:").appendField(new Blockly.FieldTextInput(""), "Z");

        this.setOutput(true, null);

    this.setColour('#212121');
    this.setTooltip("Creates a vector from X, Y, Z components");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['VECTORTOWARDS'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Vector Towards");
        this.appendDummyInput().appendField("Start Pos:").appendField(new Blockly.FieldTextInput(""), "START_POS");
    this.appendDummyInput().appendField("End Pos:").appendField(new Blockly.FieldTextInput(""), "END_POS");

        this.setOutput(true, null);

    this.setColour('#212121');
    this.setTooltip("Creates a direction vector from start to end");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['DISTANCEBETWEEN'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Distance Between");
        this.appendDummyInput().appendField("Position A:").appendField(new Blockly.FieldTextInput(""), "POSITION_A");
    this.appendDummyInput().appendField("Position B:").appendField(new Blockly.FieldTextInput(""), "POSITION_B");

        this.setOutput(true, null);

    this.setColour('#212121');
    this.setTooltip("Returns distance between two positions");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['XCOMPONENTOF'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("X Component Of");
        this.appendDummyInput().appendField("Vector:").appendField(new Blockly.FieldTextInput(""), "VECTOR");

        this.setOutput(true, null);

    this.setColour('#212121');
    this.setTooltip("Returns the X component of a vector");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['YCOMPONENTOF'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Y Component Of");
        this.appendDummyInput().appendField("Vector:").appendField(new Blockly.FieldTextInput(""), "VECTOR");

        this.setOutput(true, null);

    this.setColour('#212121');
    this.setTooltip("Returns the Y component of a vector");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['ZCOMPONENTOF'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Z Component Of");
        this.appendDummyInput().appendField("Vector:").appendField(new Blockly.FieldTextInput(""), "VECTOR");

        this.setOutput(true, null);

    this.setColour('#212121');
    this.setTooltip("Returns the Z component of a vector");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['NORMALIZE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Normalize");
        this.appendDummyInput().appendField("Vector:").appendField(new Blockly.FieldTextInput(""), "VECTOR");

        this.setOutput(true, null);

    this.setColour('#212121');
    this.setTooltip("Returns a normalized vector (length 1)");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['DOTPRODUCT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Dot Product");
        this.appendDummyInput().appendField("Vector A:").appendField(new Blockly.FieldTextInput(""), "VECTOR_A");
    this.appendDummyInput().appendField("Vector B:").appendField(new Blockly.FieldTextInput(""), "VECTOR_B");

        this.setOutput(true, null);

    this.setColour('#212121');
    this.setTooltip("Returns the dot product of two vectors");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['CROSSPRODUCT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Cross Product");
        this.appendDummyInput().appendField("Vector A:").appendField(new Blockly.FieldTextInput(""), "VECTOR_A");
    this.appendDummyInput().appendField("Vector B:").appendField(new Blockly.FieldTextInput(""), "VECTOR_B");

        this.setOutput(true, null);

    this.setColour('#212121');
    this.setTooltip("Returns the cross product of two vectors");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['VECTORMAGNITUDE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Magnitude Of");
        this.appendDummyInput().appendField("Vector:").appendField(new Blockly.FieldTextInput(""), "VECTOR");

        this.setOutput(true, null);

    this.setColour('#212121');
    this.setTooltip("Returns the length of a vector");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['UP'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Up");
    
        this.setOutput(true, null);

    this.setColour('#212121');
    this.setTooltip("Returns the up direction vector (0, 1, 0)");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['DOWN'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Down");
    
        this.setOutput(true, null);

    this.setColour('#212121');
    this.setTooltip("Returns the down direction vector (0, -1, 0)");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['LEFT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Left");
    
        this.setOutput(true, null);

    this.setColour('#212121');
    this.setTooltip("Returns the left direction vector (-1, 0, 0)");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['RIGHT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Right");
    
        this.setOutput(true, null);

    this.setColour('#212121');
    this.setTooltip("Returns the right direction vector (1, 0, 0)");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['FORWARD'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Forward");
    
        this.setOutput(true, null);

    this.setColour('#212121');
    this.setTooltip("Returns the forward direction vector (0, 0, 1)");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['BACKWARD'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Backward");
    
        this.setOutput(true, null);

    this.setColour('#212121');
    this.setTooltip("Returns the backward direction vector (0, 0, -1)");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['SHOWMESSAGE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Show Message");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Message:").appendField(new Blockly.FieldTextInput(""), "MESSAGE");
    this.appendDummyInput().appendField("Duration:").appendField(new Blockly.FieldTextInput(""), "DURATION");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#607D8B');
    this.setTooltip("Shows a message to the player");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['SHOWBIGMESSAGE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Show Big Message");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Title:").appendField(new Blockly.FieldTextInput(""), "TITLE");
    this.appendDummyInput().appendField("Subtitle:").appendField(new Blockly.FieldTextInput(""), "SUBTITLE");
    this.appendDummyInput().appendField("Duration:").appendField(new Blockly.FieldTextInput(""), "DURATION");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#607D8B');
    this.setTooltip("Shows a large message on screen");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['SHOWNOTIFICATION'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Show Notification");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Text:").appendField(new Blockly.FieldTextInput(""), "TEXT");
    this.appendDummyInput().appendField("Icon:").appendField(new Blockly.FieldTextInput(""), "ICON");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#607D8B');
    this.setTooltip("Shows a notification toast");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['SETHUDVISIBLE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set HUD Visible");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Hud Element:").appendField(new Blockly.FieldTextInput(""), "HUD_ELEMENT");
    this.appendDummyInput().appendField("Visible:").appendField(new Blockly.FieldTextInput(""), "VISIBLE");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#607D8B');
    this.setTooltip("Shows or hides specific HUD elements");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['UPDATEHUDTEXT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Update HUD Text");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Hud Id:").appendField(new Blockly.FieldTextInput(""), "HUD_ID");
    this.appendDummyInput().appendField("Text:").appendField(new Blockly.FieldTextInput(""), "TEXT");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#607D8B');
    this.setTooltip("Updates text on a custom HUD element");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['CREATECUSTOMHUD'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Create Custom HUD");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Hud Config:").appendField(new Blockly.FieldTextInput(""), "HUD_CONFIG");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#607D8B');
    this.setTooltip("Creates a custom HUD layout");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['CREATEWORLDMARKER'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Create World Marker");
        this.appendDummyInput().appendField("Location:").appendField(new Blockly.FieldTextInput(""), "LOCATION");
    this.appendDummyInput().appendField("Icon:").appendField(new Blockly.FieldTextInput(""), "ICON");
    this.appendDummyInput().appendField("Text:").appendField(new Blockly.FieldTextInput(""), "TEXT");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#607D8B');
    this.setTooltip("Creates a 3D marker in the world");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['REMOVEWORLDMARKER'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Remove World Marker");
        this.appendDummyInput().appendField("Marker Id:").appendField(new Blockly.FieldTextInput(""), "MARKER_ID");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#607D8B');
    this.setTooltip("Removes a world marker");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['SETOBJECTIVEMARKER'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set Objective Marker");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Location:").appendField(new Blockly.FieldTextInput(""), "LOCATION");
    this.appendDummyInput().appendField("Text:").appendField(new Blockly.FieldTextInput(""), "TEXT");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#607D8B');
    this.setTooltip("Sets the objective marker for a player");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['UPDATESCOREBOARD'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Update Scoreboard");
        this.appendDummyInput().appendField("Entries:").appendField(new Blockly.FieldTextInput(""), "ENTRIES");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#607D8B');
    this.setTooltip("Updates the scoreboard data");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['SHOWSCOREBOARD'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Show Scoreboard");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Visible:").appendField(new Blockly.FieldTextInput(""), "VISIBLE");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#607D8B');
    this.setTooltip("Forces the scoreboard to show or hide");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['NUMBER'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Number");
    
        this.setOutput(true, null);

    this.setColour('#0288D1');
    this.setTooltip("A numeric value");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['STRING'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("String");
    
        this.setOutput(true, null);

    this.setColour('#0288D1');
    this.setTooltip("A text value");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['BOOLEAN'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Boolean");
    
        this.setOutput(true, null);

    this.setColour('#0288D1');
    this.setTooltip("A true/false value");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['SETVARIABLE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set Variable");
        this.appendDummyInput().appendField("Variable:").appendField(new Blockly.FieldTextInput(""), "VARIABLE");
    this.appendDummyInput().appendField("Value:").appendField(new Blockly.FieldTextInput(""), "VALUE");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#0288D1');
    this.setTooltip("Sets the value of a variable");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['GETVARIABLE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get Variable");
        this.appendDummyInput().appendField("Variable Name:").appendField(new Blockly.FieldTextInput(""), "VARIABLE_NAME");

        this.setOutput(true, null);

    this.setColour('#0288D1');
    this.setTooltip("Gets the value of a variable");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['SPAWNVEHICLE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Spawn Vehicle");
        this.appendDummyInput().appendField("Vehicle Type:").appendField(new Blockly.FieldTextInput(""), "VEHICLE_TYPE");
    this.appendDummyInput().appendField("Location:").appendField(new Blockly.FieldTextInput(""), "LOCATION");
    this.appendDummyInput().appendField("Team:").appendField(new Blockly.FieldTextInput(""), "TEAM");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#E64A19');
    this.setTooltip("Spawns a vehicle at a location");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['DESPAWNVEHICLE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Despawn Vehicle");
        this.appendDummyInput().appendField("Vehicle:").appendField(new Blockly.FieldTextInput(""), "VEHICLE");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#E64A19');
    this.setTooltip("Removes a vehicle from the game");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['VEHICLETYPETANK'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Tank");
    
        this.setOutput(true, null);

    this.setColour('#E64A19');
    this.setTooltip("Tank vehicle type");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['VEHICLETYPEAPC'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("APC");
    
        this.setOutput(true, null);

    this.setColour('#E64A19');
    this.setTooltip("APC vehicle type");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['VEHICLETYPEHELICOPTER'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Helicopter");
    
        this.setOutput(true, null);

    this.setColour('#E64A19');
    this.setTooltip("Helicopter vehicle type");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['VEHICLETYPEJET'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Jet");
    
        this.setOutput(true, null);

    this.setColour('#E64A19');
    this.setTooltip("Jet vehicle type");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['VEHICLETYPETRANSPORT'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Transport");
    
        this.setOutput(true, null);

    this.setColour('#E64A19');
    this.setTooltip("Transport vehicle type");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['GETVEHICLEHEALTH'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get Vehicle Health");
        this.appendDummyInput().appendField("Vehicle:").appendField(new Blockly.FieldTextInput(""), "VEHICLE");

        this.setOutput(true, null);

    this.setColour('#E64A19');
    this.setTooltip("Returns the current health of a vehicle");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['SETVEHICLEHEALTH'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set Vehicle Health");
        this.appendDummyInput().appendField("Vehicle:").appendField(new Blockly.FieldTextInput(""), "VEHICLE");
    this.appendDummyInput().appendField("Health:").appendField(new Blockly.FieldTextInput(""), "HEALTH");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#E64A19');
    this.setTooltip("Sets the health of a vehicle");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['GETVEHICLEDRIVER'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Get Vehicle Driver");
        this.appendDummyInput().appendField("Vehicle:").appendField(new Blockly.FieldTextInput(""), "VEHICLE");

        this.setOutput(true, null);

    this.setColour('#E64A19');
    this.setTooltip("Returns the player driving the vehicle");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['EJECTFROMVEHICLE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Eject from Vehicle");
        this.appendDummyInput().appendField("Player:").appendField(new Blockly.FieldTextInput(""), "PLAYER");
    this.appendDummyInput().appendField("Vehicle:").appendField(new Blockly.FieldTextInput(""), "VEHICLE");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#E64A19');
    this.setTooltip("Forces a player out of a vehicle");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['LOCKVEHICLE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Lock Vehicle");
        this.appendDummyInput().appendField("Vehicle:").appendField(new Blockly.FieldTextInput(""), "VEHICLE");
    this.appendDummyInput().appendField("Team:").appendField(new Blockly.FieldTextInput(""), "TEAM");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#E64A19');
    this.setTooltip("Locks a vehicle for a specific team");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['SETVEHICLESPEED'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Set Vehicle Speed");
        this.appendDummyInput().appendField("Vehicle:").appendField(new Blockly.FieldTextInput(""), "VEHICLE");
    this.appendDummyInput().appendField("Speed:").appendField(new Blockly.FieldTextInput(""), "SPEED");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#E64A19');
    this.setTooltip("Sets the speed of a vehicle");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['DISABLEVEHICLE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Disable Vehicle");
        this.appendDummyInput().appendField("Vehicle:").appendField(new Blockly.FieldTextInput(""), "VEHICLE");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#E64A19');
    this.setTooltip("Disables vehicle movement and weapons");
    this.setHelpUrl("");
  }
};


Blockly.Blocks['ENABLEVEHICLE'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("Enable Vehicle");
        this.appendDummyInput().appendField("Vehicle:").appendField(new Blockly.FieldTextInput(""), "VEHICLE");

        this.setPreviousStatement(true, "Action");
    this.setNextStatement(true, "Action");

    this.setColour('#E64A19');
    this.setTooltip("Enables vehicle movement and weapons");
    this.setHelpUrl("");
  }
};

