var TOOLBOX_CONFIG = {
  'kind': 'categoryToolbox',
  'contents': [
    {
      'kind': 'category',
      'name': 'ACTIONS',
      'contents': [
        { 'kind': 'block', 'type': 'AIBattlefieldBehaviour' },
        { 'kind': 'block', 'type': 'AIDefendPositionBehaviour' },
        { 'kind': 'block', 'type': 'AIIdleBehaviour' },
        { 'kind': 'block', 'type': 'AILOSMoveTOBehaviour' },
        { 'kind': 'block', 'type': 'AIMoveToBehaviour' },
        { 'kind': 'block', 'type': 'AIParachuteBehaviour' },
        { 'kind': 'block', 'type': 'AIValidateMoveToBehaviour' },
        { 'kind': 'block', 'type': 'AIWaypointIdleBehaviour' },
        { 'kind': 'block', 'type': 'SetPlayerHealth' },
        { 'kind': 'block', 'type': 'SetPlayerLoadout' },
        { 'kind': 'block', 'type': 'Teleport' },
        { 'kind': 'block', 'type': 'EndRound' },
        { 'kind': 'block', 'type': 'PauseRound' },
      ]
    },
    {
      'kind': 'category',
      'name': 'AI',
      'contents': [
        { 'kind': 'block', 'type': 'AIBattlefieldBehavior' },
        { 'kind': 'block', 'type': 'AIDefendPositionBehavior' },
        { 'kind': 'block', 'type': 'AIIdleBehavior' },
        { 'kind': 'block', 'type': 'AIMoveToBehavior' },
        { 'kind': 'block', 'type': 'AIParachuteBehavior' },
        { 'kind': 'block', 'type': 'AIWaypointIdleBehavior' },
        { 'kind': 'block', 'type': 'AIFollowPlayer' },
        { 'kind': 'block', 'type': 'AIHoldPosition' },
        { 'kind': 'block', 'type': 'AIAttackTarget' },
        { 'kind': 'block', 'type': 'SetAIBehavior' },
        { 'kind': 'block', 'type': 'DeployAI' },
        { 'kind': 'block', 'type': 'DespawnAI' },
        { 'kind': 'block', 'type': 'SetAISpawnLocation' },
        { 'kind': 'block', 'type': 'SetAIHealth' },
        { 'kind': 'block', 'type': 'SetAITeam' },
        { 'kind': 'block', 'type': 'GetAIHealth' },
        { 'kind': 'block', 'type': 'GetAITeam' },
        { 'kind': 'block', 'type': 'AIIsAlive' },
      ]
    },
    {
      'kind': 'category',
      'name': 'ARRAYS',
      'contents': [
        { 'kind': 'block', 'type': 'SetVariableAtIndex' },
        { 'kind': 'block', 'type': 'EmptyArray' },
        { 'kind': 'block', 'type': 'ArrayLiteral' },
        { 'kind': 'block', 'type': 'ArrayOfSize' },
        { 'kind': 'block', 'type': 'ArrayFromPlayers' },
        { 'kind': 'block', 'type': 'ArrayFromDeadPlayers' },
        { 'kind': 'block', 'type': 'ArrayFromLivingPlayers' },
        { 'kind': 'block', 'type': 'ClearArray' },
        { 'kind': 'block', 'type': 'ConcatArrays' },
        { 'kind': 'block', 'type': 'ReverseArray' },
        { 'kind': 'block', 'type': 'AppendToArray' },
        { 'kind': 'block', 'type': 'RemoveFromArray' },
        { 'kind': 'block', 'type': 'RemoveFromArrayByIndex' },
        { 'kind': 'block', 'type': 'ArraySlice' },
        { 'kind': 'block', 'type': 'RandomValueInArray' },
        { 'kind': 'block', 'type': 'ValueInArray' },
        { 'kind': 'block', 'type': 'FirstOf' },
        { 'kind': 'block', 'type': 'LastOf' },
        { 'kind': 'block', 'type': 'IndexOfArrayValue' },
        { 'kind': 'block', 'type': 'CountOf' },
        { 'kind': 'block', 'type': 'ArrayContains' },
        { 'kind': 'block', 'type': 'ForEachInArray' },
        { 'kind': 'block', 'type': 'MapArray' },
        { 'kind': 'block', 'type': 'FilteredArray' },
        { 'kind': 'block', 'type': 'SortedArray' },
      ]
    },
    {
      'kind': 'category',
      'name': 'AUDIO',
      'contents': [
        { 'kind': 'block', 'type': 'LoadMusic' },
        { 'kind': 'block', 'type': 'PlayMusic' },
        { 'kind': 'block', 'type': 'SetMusicParam' },
        { 'kind': 'block', 'type': 'UnloadMusic' },
        { 'kind': 'block', 'type': 'PlaySound' },
        { 'kind': 'block', 'type': 'PlayVO' },
        { 'kind': 'block', 'type': 'StopSound' },
      ]
    },
    {
      'kind': 'category',
      'name': 'CAMERA',
      'contents': [
        { 'kind': 'block', 'type': 'SetPlayerCamera' },
        { 'kind': 'block', 'type': 'LockCameraToTarget' },
        { 'kind': 'block', 'type': 'CameraShake' },
        { 'kind': 'block', 'type': 'SetCameraFOV' },
        { 'kind': 'block', 'type': 'ResetCamera' },
        { 'kind': 'block', 'type': 'FirstPersonCamera' },
        { 'kind': 'block', 'type': 'ThirdPersonCamera' },
        { 'kind': 'block', 'type': 'FreeCamera' },
        { 'kind': 'block', 'type': 'SpectatorCamera' },
      ]
    },
    {
      'kind': 'category',
      'name': 'CONDITIONS',
      'contents': [
        { 'kind': 'block', 'type': 'Equal' },
        { 'kind': 'block', 'type': 'NotEqual' },
        { 'kind': 'block', 'type': 'LessThan' },
        { 'kind': 'block', 'type': 'LessThanOrEqual' },
        { 'kind': 'block', 'type': 'GreaterThan' },
        { 'kind': 'block', 'type': 'GreaterThanOrEqual' },
        { 'kind': 'block', 'type': 'And' },
        { 'kind': 'block', 'type': 'Or' },
        { 'kind': 'block', 'type': 'Not' },
        { 'kind': 'block', 'type': 'True' },
        { 'kind': 'block', 'type': 'False' },
      ]
    },
    {
      'kind': 'category',
      'name': 'EFFECTS',
      'contents': [
        { 'kind': 'block', 'type': 'PlayEffect' },
        { 'kind': 'block', 'type': 'StopEffect' },
        { 'kind': 'block', 'type': 'ParticleEffect' },
        { 'kind': 'block', 'type': 'ExplosionEffect' },
        { 'kind': 'block', 'type': 'ScreenFlash' },
        { 'kind': 'block', 'type': 'ScreenFade' },
        { 'kind': 'block', 'type': 'ApplyScreenFilter' },
      ]
    },
    {
      'kind': 'category',
      'name': 'EMPLACEMENTS',
      'contents': [
        { 'kind': 'block', 'type': 'DeployEmplacement' },
      ]
    },
    {
      'kind': 'category',
      'name': 'EVENTS',
      'contents': [
        { 'kind': 'block', 'type': 'ON_START' },
        { 'kind': 'block', 'type': 'ON_PLAYER_JOIN' },
        { 'kind': 'block', 'type': 'EventAttacker' },
        { 'kind': 'block', 'type': 'EventDamage' },
        { 'kind': 'block', 'type': 'EventLocation' },
        { 'kind': 'block', 'type': 'EventPlayer' },
        { 'kind': 'block', 'type': 'EventTeam' },
        { 'kind': 'block', 'type': 'EventVictim' },
        { 'kind': 'block', 'type': 'EventWeapon' },
      ]
    },
    {
      'kind': 'category',
      'name': 'GAMEPLAY',
      'contents': [
        { 'kind': 'block', 'type': 'EndMatch' },
        { 'kind': 'block', 'type': 'SetMatchTime' },
        { 'kind': 'block', 'type': 'GetMatchTime' },
        { 'kind': 'block', 'type': 'PauseMatchTime' },
        { 'kind': 'block', 'type': 'ResumeMatchTime' },
        { 'kind': 'block', 'type': 'SetTeamScore' },
        { 'kind': 'block', 'type': 'GetTeamScore' },
        { 'kind': 'block', 'type': 'ModifyTeamScore' },
        { 'kind': 'block', 'type': 'DeclarePlayerTeamWinner' },
        { 'kind': 'block', 'type': 'SetRespawnTime' },
        { 'kind': 'block', 'type': 'DisableRespawn' },
        { 'kind': 'block', 'type': 'EnableRespawn' },
        { 'kind': 'block', 'type': 'GetGlobalVariable' },
        { 'kind': 'block', 'type': 'SetGlobalVariable' },
        { 'kind': 'block', 'type': 'ModifyGlobalVariable' },
      ]
    },
    {
      'kind': 'category',
      'name': 'LOGIC',
      'contents': [
        { 'kind': 'block', 'type': 'Wait' },
        { 'kind': 'block', 'type': 'WaitUntil' },
        { 'kind': 'block', 'type': 'Break' },
        { 'kind': 'block', 'type': 'Continue' },
        { 'kind': 'block', 'type': 'If' },
        { 'kind': 'block', 'type': 'While' },
        { 'kind': 'block', 'type': 'And' },
        { 'kind': 'block', 'type': 'Or' },
        { 'kind': 'block', 'type': 'Not' },
        { 'kind': 'block', 'type': 'True' },
        { 'kind': 'block', 'type': 'False' },
        { 'kind': 'block', 'type': 'Equal' },
        { 'kind': 'block', 'type': 'NotEqual' },
        { 'kind': 'block', 'type': 'GreaterThan' },
        { 'kind': 'block', 'type': 'LessThan' },
        { 'kind': 'block', 'type': 'GreaterThanEqual' },
        { 'kind': 'block', 'type': 'LessThanEqual' },
        { 'kind': 'block', 'type': 'ForVariable' },
      ]
    },
    {
      'kind': 'category',
      'name': 'MATH',
      'contents': [
        { 'kind': 'block', 'type': 'Add' },
        { 'kind': 'block', 'type': 'Subtract' },
        { 'kind': 'block', 'type': 'Multiply' },
        { 'kind': 'block', 'type': 'Divide' },
        { 'kind': 'block', 'type': 'Modulo' },
        { 'kind': 'block', 'type': 'RaiseToPower' },
        { 'kind': 'block', 'type': 'Sine' },
        { 'kind': 'block', 'type': 'Cosine' },
        { 'kind': 'block', 'type': 'Tangent' },
        { 'kind': 'block', 'type': 'ArcSine' },
        { 'kind': 'block', 'type': 'ArcCosine' },
        { 'kind': 'block', 'type': 'ArcTangent' },
        { 'kind': 'block', 'type': 'Round' },
        { 'kind': 'block', 'type': 'Ceil' },
        { 'kind': 'block', 'type': 'Floor' },
        { 'kind': 'block', 'type': 'RandomInteger' },
        { 'kind': 'block', 'type': 'RandomReal' },
        { 'kind': 'block', 'type': 'AbsoluteValue' },
        { 'kind': 'block', 'type': 'SquareRoot' },
        { 'kind': 'block', 'type': 'Min' },
        { 'kind': 'block', 'type': 'Max' },
        { 'kind': 'block', 'type': 'RoundToInteger' },
      ]
    },
    {
      'kind': 'category',
      'name': 'OBJECTIVE',
      'contents': [
        { 'kind': 'block', 'type': 'SetObjectiveState' },
        { 'kind': 'block', 'type': 'GetObjectiveState' },
      ]
    },
    {
      'kind': 'category',
      'name': 'OTHER',
      'contents': [
        { 'kind': 'block', 'type': 'Comment' },
      ]
    },
    {
      'kind': 'category',
      'name': 'PLAYER',
      'contents': [
        { 'kind': 'block', 'type': 'EventPlayer' },
        { 'kind': 'block', 'type': 'GetPlayerHealth' },
        { 'kind': 'block', 'type': 'GetPlayerMaxHealth' },
        { 'kind': 'block', 'type': 'IsPlayerAlive' },
        { 'kind': 'block', 'type': 'IsPlayerDead' },
        { 'kind': 'block', 'type': 'GetPlayerTeam' },
        { 'kind': 'block', 'type': 'SetPlayerHealth' },
        { 'kind': 'block', 'type': 'KillPlayer' },
        { 'kind': 'block', 'type': 'RespawnPlayer' },
        { 'kind': 'block', 'type': 'TeleportPlayer' },
        { 'kind': 'block', 'type': 'SetPlayerMaxHealth' },
        { 'kind': 'block', 'type': 'GetPlayerPosition' },
        { 'kind': 'block', 'type': 'GetPlayerVelocity' },
        { 'kind': 'block', 'type': 'GetPlayerSpeed' },
        { 'kind': 'block', 'type': 'GetPlayerFacingDirection' },
        { 'kind': 'block', 'type': 'GetPlayerVariable' },
        { 'kind': 'block', 'type': 'SetPlayerVariable' },
        { 'kind': 'block', 'type': 'ModifyPlayerVariable' },
        { 'kind': 'block', 'type': 'EnablePlayerInput' },
        { 'kind': 'block', 'type': 'GetPlayerPosition' },
        { 'kind': 'block', 'type': 'Teleport' },
      ]
    },
    {
      'kind': 'category',
      'name': 'TRANSFORM',
      'contents': [
        { 'kind': 'block', 'type': 'Vector' },
        { 'kind': 'block', 'type': 'VectorTowards' },
        { 'kind': 'block', 'type': 'DistanceBetween' },
        { 'kind': 'block', 'type': 'XComponentOf' },
        { 'kind': 'block', 'type': 'YComponentOf' },
        { 'kind': 'block', 'type': 'ZComponentOf' },
        { 'kind': 'block', 'type': 'Normalize' },
        { 'kind': 'block', 'type': 'DotProduct' },
        { 'kind': 'block', 'type': 'CrossProduct' },
        { 'kind': 'block', 'type': 'VectorMagnitude' },
        { 'kind': 'block', 'type': 'Up' },
        { 'kind': 'block', 'type': 'Down' },
        { 'kind': 'block', 'type': 'Left' },
        { 'kind': 'block', 'type': 'Right' },
        { 'kind': 'block', 'type': 'Forward' },
        { 'kind': 'block', 'type': 'Backward' },
      ]
    },
    {
      'kind': 'category',
      'name': 'UI',
      'contents': [
        { 'kind': 'block', 'type': 'ShowMessage' },
        { 'kind': 'block', 'type': 'ShowBigMessage' },
        { 'kind': 'block', 'type': 'ShowNotification' },
        { 'kind': 'block', 'type': 'SetHUDVisible' },
        { 'kind': 'block', 'type': 'UpdateHUDText' },
        { 'kind': 'block', 'type': 'CreateCustomHUD' },
        { 'kind': 'block', 'type': 'CreateWorldMarker' },
        { 'kind': 'block', 'type': 'RemoveWorldMarker' },
        { 'kind': 'block', 'type': 'SetObjectiveMarker' },
        { 'kind': 'block', 'type': 'UpdateScoreboard' },
        { 'kind': 'block', 'type': 'ShowScoreboard' },
      ]
    },
    {
      'kind': 'category',
      'name': 'VALUES',
      'contents': [
        { 'kind': 'block', 'type': 'Number' },
        { 'kind': 'block', 'type': 'String' },
        { 'kind': 'block', 'type': 'Boolean' },
        { 'kind': 'block', 'type': 'SetVariable' },
        { 'kind': 'block', 'type': 'GetVariable' },
      ]
    },
    {
      'kind': 'category',
      'name': 'VEHICLES',
      'contents': [
        { 'kind': 'block', 'type': 'SpawnVehicle' },
        { 'kind': 'block', 'type': 'DespawnVehicle' },
        { 'kind': 'block', 'type': 'VehicleTypeTank' },
        { 'kind': 'block', 'type': 'VehicleTypeAPC' },
        { 'kind': 'block', 'type': 'VehicleTypeHelicopter' },
        { 'kind': 'block', 'type': 'VehicleTypeJet' },
        { 'kind': 'block', 'type': 'VehicleTypeTransport' },
        { 'kind': 'block', 'type': 'GetVehicleHealth' },
        { 'kind': 'block', 'type': 'SetVehicleHealth' },
        { 'kind': 'block', 'type': 'GetVehicleDriver' },
        { 'kind': 'block', 'type': 'EjectFromVehicle' },
        { 'kind': 'block', 'type': 'LockVehicle' },
        { 'kind': 'block', 'type': 'SetVehicleSpeed' },
        { 'kind': 'block', 'type': 'DisableVehicle' },
        { 'kind': 'block', 'type': 'EnableVehicle' },
      ]
    },
  ]
};
