/**
 * @license
 * Copyright 2023 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

export const toolbox = {
  "kind": "categoryToolbox",
  "contents": [
    {
      "kind": "category",
      "name": "RULES",
      "colour": "#6E47A0",
      "contents": [
        { "kind": "block", "type": "MOD_BLOCK" },
        { "kind": "block", "type": "RULE_HEADER" },
        { "kind": "block", "type": "CONDITION_BLOCK" },
        { "kind": "block", "type": "COMMENT" }
      ]
    },
    // --- YELLOW MENUS (Statements) ---
    {
      "kind": "category",
      "name": "AI",
      "colour": "#FFEB3B",
      "contents": [
        { "kind": "block", "type": "AIBATTLEFIELDBEHAVIOUR" },
        { "kind": "block", "type": "AIDEFENDPOSITIONBEHAVIOUR" },
        { "kind": "block", "type": "AIIDLEBEHAVIOUR" },
        { "kind": "block", "type": "AILOSMOVETOBEHAVIOUR" },
        { "kind": "block", "type": "AIMOVETOBEHAVIOUR" },
        { "kind": "block", "type": "AIPARACHUTEBEHAVIOUR" },
        { "kind": "block", "type": "AIVALIDATEMOVETOBEHAVIOUR" },
        { "kind": "block", "type": "AIWAYPOINTIDLEBEHAVIOUR" },
        { "kind": "block", "type": "SETAIBEHAVIOR" },
        { "kind": "block", "type": "DEPLOYAI" },
        { "kind": "block", "type": "DESPAWNAI" },
        { "kind": "block", "type": "SETAISPAWNLOCATION" },
        { "kind": "block", "type": "SETAIHEALTH" },
        { "kind": "block", "type": "SETAITEAM" },
        { "kind": "block", "type": "AIBATTLEFIELDBEHAVIOR" },
        { "kind": "block", "type": "AIDEFENDPOSITIONBEHAVIOR" },
        { "kind": "block", "type": "AIIDLEBEHAVIOR" },
        { "kind": "block", "type": "AIMOVETOBEHAVIOR" },
        { "kind": "block", "type": "AIPARACHUTEBEHAVIOR" },
        { "kind": "block", "type": "AIWAYPOINTIDLEBEHAVIOR" },
        { "kind": "block", "type": "AIFOLLOWPLAYER" },
        { "kind": "block", "type": "AIHOLDPOSITION" },
        { "kind": "block", "type": "AIATTACKTARGET" },
        { "kind": "block", "type": "mod_AISetUnspawnOnDead" },
        { "kind": "block", "type": "mod_SetUnspawnDelayInSeconds" },
        { "kind": "block", "type": "mod_SpawnAIFromAISpawner_Spawner" },
        { "kind": "block", "type": "mod_UnspawnAllAIsFromAISpawner" },
        { "kind": "block", "type": "mod_AIEnableShooting_Enable" },
        { "kind": "block", "type": "mod_AIEnableTargeting_Enable" },
        { "kind": "block", "type": "mod_AIForceFire" },
        { "kind": "block", "type": "mod_AIGadgetSettings" },
        { "kind": "block", "type": "mod_AISetFocusPoint" },
        { "kind": "block", "type": "mod_AISetMoveSpeed" },
        { "kind": "block", "type": "mod_AISetStance" },
        { "kind": "block", "type": "mod_AISetTarget_Player" },
        { "kind": "block", "type": "mod_AIStartUsingGadget" },
        { "kind": "block", "type": "mod_AIStopUsingGadget" },
        { "kind": "block", "type": "mod_SetAIToHumanDamageModifier" }
      ]
    },
    {
      "kind": "category",
      "name": "ARRAYS",
      "colour": "#FFEB3B",
      "contents": [
        { "kind": "block", "type": "CREATEARRAY" },
        { "kind": "block", "type": "SETELEMENT" },
        { "kind": "block", "type": "APPENDTOARRAY" },
        { "kind": "block", "type": "REMOVEFROMARRAY" },
        { "kind": "block", "type": "SORTARRAY" },
        { "kind": "block", "type": "remove_from_array" },
        { "kind": "block", "type": "remove_player_inventory" },
        { "kind": "block", "type": "remove_player_inventory_at_slot" }
      ]
    },
    {
      "kind": "category",
      "name": "AUDIO",
      "colour": "#FFEB3B",
      "contents": [
        { "kind": "block", "type": "LOADMUSIC" },
        { "kind": "block", "type": "PLAYMUSIC" },
        { "kind": "block", "type": "SETMUSICPARAM" },
        { "kind": "block", "type": "UNLOADMUSIC" },
        { "kind": "block", "type": "PLAYSOUND" },
        { "kind": "block", "type": "PLAYVO" },
        { "kind": "block", "type": "STOPSOUND" },
        { "kind": "block", "type": "enable_vo_messaging" },
        { "kind": "block", "type": "trigger_audio" },
        { "kind": "block", "type": "trigger_audio_at_location" },
        { "kind": "block", "type": "mod_PlaySound_Amplitude" },
        { "kind": "block", "type": "mod_PlaySound_Team" },
        { "kind": "block", "type": "mod_PlaySound_Attenuationrange" },
        { "kind": "block", "type": "mod_PlayVO_Flag" },
        { "kind": "block", "type": "mod_PlayVO_Player" },
        { "kind": "block", "type": "mod_StopSound_Objectid" }
      ]
    },
    {
      "kind": "category",
      "name": "CAMERA",
      "colour": "#FFEB3B",
      "contents": [
        { "kind": "block", "type": "SETPLAYERCAMERA" },
        { "kind": "block", "type": "LOCKCAMERATOTARGET" },
        { "kind": "block", "type": "CAMERASHAKE" },
        { "kind": "block", "type": "SETCAMERAFOV" },
        { "kind": "block", "type": "RESETCAMERA" },
        { "kind": "block", "type": "mod_SetCameraTypeForAll_Cameratype" },
        { "kind": "block", "type": "mod_SetCameraTypeForPlayer_Cameratype" }
      ]
    },
    {
      "kind": "category",
      "name": "EFFECTS",
      "colour": "#FFEB3B",
      "contents": [
        { "kind": "block", "type": "PLAYEFFECT" },
        { "kind": "block", "type": "STOPEFFECT" },
        { "kind": "block", "type": "PARTICLEEFFECT" },
        { "kind": "block", "type": "EXPLOSIONEFFECT" },
        { "kind": "block", "type": "SCREENFLASH" },
        { "kind": "block", "type": "SCREENFADE" },
        { "kind": "block", "type": "APPLYSCREENFILTER" },
        { "kind": "block", "type": "mod_EnableScreenEffect" },
        { "kind": "block", "type": "mod_EnableVFX" },
        { "kind": "block", "type": "mod_MoveVFX" },
        { "kind": "block", "type": "mod_SetVFXColor" },
        { "kind": "block", "type": "mod_SetVFXScale" },
        { "kind": "block", "type": "mod_SetVFXSpeed" }
      ]
    },
    {
      "kind": "category",
      "name": "EMPLACEMENTS",
      "colour": "#FFEB3B",
      "contents": [
        { "kind": "block", "type": "DEPLOYEMPLACEMENT" },
        { "kind": "block", "type": "mod_ForceEmplacementSpawnerSpawn" },
        { "kind": "block", "type": "mod_SetEmplacementSpawnerAbandonVehicleOutOfCombatArea" },
        { "kind": "block", "type": "mod_SetEmplacementSpawnerApplyDamageToAbandonVehicle" },
        { "kind": "block", "type": "mod_SetEmplacementSpawnerAutoSpawn" },
        { "kind": "block", "type": "mod_SetEmplacementSpawnerKeepAliveAbandonRadius" },
        { "kind": "block", "type": "mod_SetEmplacementSpawnerRespawnTime" },
        { "kind": "block", "type": "mod_SetEmplacementSpawnerSpawnerRadius" },
        { "kind": "block", "type": "mod_SetEmplacementSpawnerTimeUntilAbandon" },
        { "kind": "block", "type": "mod_SetEmplacementSpawnerType" }
      ]
    },
    {
      "kind": "category",
      "name": "GAMEPLAY",
      "colour": "#FFEB3B",
      "contents": [
        { "kind": "block", "type": "ON_START" },
        { "kind": "block", "type": "ON_PLAYER_JOIN" },
        { "kind": "block", "type": "ENDROUND" },
        { "kind": "block", "type": "PAUSEROUND" },
        { "kind": "block", "type": "SETGAMEMODE" },
        { "kind": "block", "type": "ENABLEFRIENDLYFIRE" },
        { "kind": "block", "type": "SETSCORE" },
        { "kind": "block", "type": "SETTIMELIMIT" },
        { "kind": "block", "type": "enable_default_game_mode_scoring" },
        { "kind": "block", "type": "enable_default_game_mode_win_condition" },
        { "kind": "block", "type": "enable_game_mode_objective" },
        { "kind": "block", "type": "enable_hq" },
        { "kind": "block", "type": "enable_ticket_bleed_acceleration" },
        { "kind": "block", "type": "end_game_mode" },
        { "kind": "block", "type": "pause_game_mode_time" },
        { "kind": "block", "type": "reset_game_mode_time" },
        { "kind": "block", "type": "set_game_mode_score" },
        { "kind": "block", "type": "set_game_mode_target_score" },
        { "kind": "block", "type": "set_game_mode_time_limit" },
        { "kind": "block", "type": "set_mcom_fuse_time" },
        { "kind": "block", "type": "set_neutralization_time_multiplier" },
        { "kind": "block", "type": "set_redeploy_time" },
        { "kind": "block", "type": "track_variable_over_time" },
        { "kind": "block", "type": "mod_DeployAllPlayers" },
        { "kind": "block", "type": "mod_EnableAllPlayerDeploy" },
        { "kind": "block", "type": "mod_EnablePlayerDeploy" },
        { "kind": "block", "type": "mod_SetRedeployTime" },
        { "kind": "block", "type": "mod_UndeployAllPlayers" },
        { "kind": "block", "type": "mod_UndeployPlayer" },
        { "kind": "block", "type": "mod_EndGameMode" },
        { "kind": "block", "type": "mod_PauseGameModeTime" },
        { "kind": "block", "type": "mod_ResetGameModeTime" },
        { "kind": "block", "type": "mod_RingOfFireStart" },
        { "kind": "block", "type": "mod_SetFriendlyFire" },
        { "kind": "block", "type": "mod_SetGameModeScore" },
        { "kind": "block", "type": "mod_SetGameModeTargetScore" },
        { "kind": "block", "type": "mod_SetGameModeTimeLimit" },
        { "kind": "block", "type": "mod_SetHQTeam" },
        { "kind": "block", "type": "mod_SetRingOfFireDamageAmount" },
        { "kind": "block", "type": "mod_SetRingOfFireStableTime" },
        { "kind": "block", "type": "mod_DisablePlayerJoin" },
        { "kind": "block", "type": "mod_EnableAreaTrigger" },
        { "kind": "block", "type": "mod_EnableInteractPoint" },
        { "kind": "block", "type": "mod_EnableSpatialObject" },
        { "kind": "block", "type": "mod_SetTeam" },
        { "kind": "block", "type": "mod_SpawnLoot" },
        { "kind": "block", "type": "mod_SwitchTeams" },
        { "kind": "block", "type": "mod_UnspawnAllLoot" },
        { "kind": "block", "type": "mod_UnspawnObject" }
      ]
    },
    {
      "kind": "category",
      "name": "LOGIC",
      "colour": "#FFEB3B",
      "contents": [
        { "kind": "block", "type": "WAIT" },
        { "kind": "block", "type": "WAITUNTIL" },
        { "kind": "block", "type": "ABORT" },
        { "kind": "block", "type": "AbortIf" },
        { "kind": "block", "type": "BREAK" },
        { "kind": "block", "type": "CONTINUE" },
        { "kind": "block", "type": "IF" },
        { "kind": "block", "type": "WHILE" },
        { "kind": "block", "type": "abort" },
        { "kind": "block", "type": "abort_if" },
        { "kind": "block", "type": "break" },
        { "kind": "block", "type": "continue" },
        { "kind": "block", "type": "else_if" },
        { "kind": "block", "type": "if" },
        { "kind": "block", "type": "skip" },
        { "kind": "block", "type": "skip_if" },
        { "kind": "block", "type": "wait" },
        { "kind": "block", "type": "wait_until" },
        { "kind": "block", "type": "while" },
        { "kind": "block", "type": "loop_variable" },
        { "kind": "block", "type": "mod_ChaseVariableAtRate" },
        { "kind": "block", "type": "mod_ChaseVariableOverTime" },
        { "kind": "block", "type": "mod_StopChasingVariable" }
      ]
    },
    {
      "kind": "category",
      "name": "OBJECTIVE",
      "colour": "#FFEB3B",
      "contents": [
        { "kind": "block", "type": "capture_point_capturing_time" },
        { "kind": "block", "type": "capture_point_neutralization_time" },
        { "kind": "block", "type": "enable_capture_point_deploying" },
        { "kind": "block", "type": "enable_capturing" },
        { "kind": "block", "type": "set_capture_multiplier" },
        { "kind": "block", "type": "set_objective_owner" },
        { "kind": "block", "type": "mod_EnableCapturePointDeploying" },
        { "kind": "block", "type": "mod_SetCapturePointCapturingTime" },
        { "kind": "block", "type": "mod_SetCapturePointNeutralizationTime" },
        { "kind": "block", "type": "mod_SetCapturePointOwner" },
        { "kind": "block", "type": "mod_SetMaxCaptureMultiplier" },
        { "kind": "block", "type": "mod_EnableHQ" },
        { "kind": "block", "type": "mod_EnableGameModeObjective" },
        { "kind": "block", "type": "mod_SetMCOMFuseTime" }
      ]
    },
    {
      "kind": "category",
      "name": "OTHER",
      "colour": "#FFEB3B",
      "contents": [
        { "kind": "block", "type": "clear_all_custom_messages" },
        { "kind": "block", "type": "clear_custom_message" },
        { "kind": "block", "type": "display_custom_message" },
        { "kind": "block", "type": "display_game_mode_message" },
        { "kind": "block", "type": "display_highlighted_world_log_message" },
        { "kind": "block", "type": "display_notification_message" },
        { "kind": "block", "type": "send_error_report" }
      ]
    },
    {
      "kind": "category",
      "name": "PLAYER",
      "colour": "#FFEB3B",
      "contents": [
        { "kind": "block", "type": "SETPLAYERHEALTH" },
        { "kind": "block", "type": "SETPLAYERLOADOUT" },
        { "kind": "block", "type": "TELEPORT" },
        { "kind": "block", "type": "apply_med_gadget" },
        { "kind": "block", "type": "deal_damage" },
        { "kind": "block", "type": "deploy_all_players" },
        { "kind": "block", "type": "deploy_player" },
        { "kind": "block", "type": "enable_all_input_restrictions" },
        { "kind": "block", "type": "enable_all_player_deploy" },
        { "kind": "block", "type": "enable_input_restriction" },
        { "kind": "block", "type": "enable_player_deploy" },
        { "kind": "block", "type": "force_mandown" },
        { "kind": "block", "type": "force_revive" },
        { "kind": "block", "type": "force_switch_inventory" },
        { "kind": "block", "type": "heal" },
        { "kind": "block", "type": "kill" },
        { "kind": "block", "type": "remove_player_inventory" },
        { "kind": "block", "type": "remove_player_inventory_at_slot" },
        { "kind": "block", "type": "replace_player_inventory" },
        { "kind": "block", "type": "resupply" },
        { "kind": "block", "type": "set_inventory_ammo" },
        { "kind": "block", "type": "set_inventory_magazine_ammo" },
        { "kind": "block", "type": "set_player_max_health" },
        { "kind": "block", "type": "set_player_soldier" },
        { "kind": "block", "type": "set_redeploy_time" },
        { "kind": "block", "type": "set_team_id" },
        { "kind": "block", "type": "spot_target" },
        { "kind": "block", "type": "spot_target_for_player" },
        { "kind": "block", "type": "teleport" },
        { "kind": "block", "type": "undeploy_all_players" },
        { "kind": "block", "type": "undeploy_player" },
        { "kind": "block", "type": "unspot_target" },
        { "kind": "block", "type": "mod_DeployPlayer" },
        { "kind": "block", "type": "mod_SetSpawnMode" },
        { "kind": "block", "type": "mod_SpawnPlayerFromSpawnPoint" },
        { "kind": "block", "type": "mod_SetPlayerIncomingDamageFactor" },
        { "kind": "block", "type": "mod_Teleport" },
        { "kind": "block", "type": "mod_EnableAllInputRestrictions" },
        { "kind": "block", "type": "mod_EnableInputRestriction" },
        { "kind": "block", "type": "mod_AddAttachmentToWeaponPackage" },
        { "kind": "block", "type": "mod_AddEquipment_Weapon" },
        { "kind": "block", "type": "mod_AddEquipment_Weaponpackage" },
        { "kind": "block", "type": "mod_AddEquipment_Desiredinventoryslots" },
        { "kind": "block", "type": "mod_ForceSwitchInventory" },
        { "kind": "block", "type": "mod_RemoveEquipment" },
        { "kind": "block", "type": "mod_SetInventoryAmmo" },
        { "kind": "block", "type": "mod_SetInventoryMagazineAmmo" },
        { "kind": "block", "type": "mod_ForceManDown" },
        { "kind": "block", "type": "mod_Resupply" },
        { "kind": "block", "type": "mod_SetPlayerMaxHealth" },
        { "kind": "block", "type": "mod_SetPlayerMovementSpeedMultiplier" },
        { "kind": "block", "type": "mod_SkipManDown" }
      ]
    },
    {
      "kind": "category",
      "name": "TRANSFORM",
      "colour": "#FFEB3B",
      "contents": [
        { "kind": "block", "type": "mod_MoveObject_Positiondelta" },
        { "kind": "block", "type": "mod_MoveObject_Rotationdelta" },
        { "kind": "block", "type": "mod_MoveObjectOverTime" },
        { "kind": "block", "type": "mod_OrbitObjectOverTime_Clockwise" },
        { "kind": "block", "type": "mod_OrbitObjectOverTime_Orbitaxis" },
        { "kind": "block", "type": "mod_RotateObject" },
        { "kind": "block", "type": "mod_SetObjectTransform" },
        { "kind": "block", "type": "mod_SetObjectTransformOverTime" },
        { "kind": "block", "type": "mod_StopActiveMovementForObject" }
      ]
    },
    {
      "kind": "category",
      "name": "USER INTERFACE",
      "colour": "#FFEB3B",
      "contents": [
        { "kind": "block", "type": "SHOWMESSAGE" },
        { "kind": "block", "type": "SHOWBIGMESSAGE" },
        { "kind": "block", "type": "SHOWNOTIFICATION" },
        { "kind": "block", "type": "SETHUDVISIBLE" },
        { "kind": "block", "type": "UPDATEHUDTEXT" },
        { "kind": "block", "type": "CREATECUSTOMHUD" },
        { "kind": "block", "type": "CREATEWORLDMARKER" },
        { "kind": "block", "type": "REMOVEWORLDMARKER" },
        { "kind": "block", "type": "SETOBJECTIVEMARKER" },
        { "kind": "block", "type": "UPDATESCOREBOARD" },
        { "kind": "block", "type": "SHOWSCOREBOARD" },
        { "kind": "block", "type": "enable_world_icon_image" },
        { "kind": "block", "type": "enable_world_icon_text" },
        { "kind": "block", "type": "set_world_icon_image" },
        { "kind": "block", "type": "set_world_icon_owner" },
        { "kind": "block", "type": "set_world_icon_position" },
        { "kind": "block", "type": "set_world_icon_text" },
        { "kind": "block", "type": "send_error_report" },
        { "kind": "block", "type": "clear_all_custom_messages" },
        { "kind": "block", "type": "clear_custom_message" },
        { "kind": "block", "type": "display_custom_message" },
        { "kind": "block", "type": "display_game_mode_message" },
        { "kind": "block", "type": "display_highlighted_world_log_message" },
        { "kind": "block", "type": "display_notification_message" },
        { "kind": "block", "type": "mod_AddUIIcon_Visibility" },
        { "kind": "block", "type": "mod_AddUIIcon_Icontext" },
        { "kind": "block", "type": "mod_EnableWorldIconImage" },
        { "kind": "block", "type": "mod_EnableWorldIconText" },
        { "kind": "block", "type": "mod_RemoveUIIcon_Objectwithicon" },
        { "kind": "block", "type": "mod_RemoveUIIcon_Visibility" },
        { "kind": "block", "type": "mod_SetWorldIconColor" },
        { "kind": "block", "type": "mod_SetWorldIconImage" },
        { "kind": "block", "type": "mod_SetWorldIconOwner" },
        { "kind": "block", "type": "mod_SetWorldIconPosition" },
        { "kind": "block", "type": "mod_SetWorldIconText" },
        { "kind": "block", "type": "mod_ClearAllCustomNotificationMessages" },
        { "kind": "block", "type": "mod_ClearCustomNotificationMessage_Slot" },
        { "kind": "block", "type": "mod_ClearCustomNotificationMessage_Target" },
        { "kind": "block", "type": "mod_DisplayCustomNotificationMessage_Duration" },
        { "kind": "block", "type": "mod_DisplayCustomNotificationMessage_Target" },
        { "kind": "block", "type": "mod_DisplayHighlightedWorldLogMessage_Message" },
        { "kind": "block", "type": "mod_DisplayHighlightedWorldLogMessage_Player" },
        { "kind": "block", "type": "mod_DisplayNotificationMessage_Message" },
        { "kind": "block", "type": "mod_DisplayNotificationMessage_Player" },
        { "kind": "block", "type": "mod_SendErrorReport" },
        { "kind": "block", "type": "mod_SetScoreboardColumnNames_Column5name" },
        { "kind": "block", "type": "mod_SetScoreboardColumnNames_Column4name" },
        { "kind": "block", "type": "mod_SetScoreboardColumnNames_Column3name" },
        { "kind": "block", "type": "mod_SetScoreboardColumnNames_Column2name" },
        { "kind": "block", "type": "mod_SetScoreboardColumnNames_Column1name" },
        { "kind": "block", "type": "mod_SetScoreboardColumnWidths_Column5width" },
        { "kind": "block", "type": "mod_SetScoreboardColumnWidths_Column4width" },
        { "kind": "block", "type": "mod_SetScoreboardColumnWidths_Column3width" },
        { "kind": "block", "type": "mod_SetScoreboardColumnWidths_Column2width" },
        { "kind": "block", "type": "mod_SetScoreboardColumnWidths_Column1width" },
        { "kind": "block", "type": "mod_SetScoreboardHeader_Team2name" },
        { "kind": "block", "type": "mod_SetScoreboardHeader_Headername" },
        { "kind": "block", "type": "mod_SetScoreboardPlayerValues_Column5value" },
        { "kind": "block", "type": "mod_SetScoreboardPlayerValues_Column4value" },
        { "kind": "block", "type": "mod_SetScoreboardPlayerValues_Column3value" },
        { "kind": "block", "type": "mod_SetScoreboardPlayerValues_Column2value" },
        { "kind": "block", "type": "mod_SetScoreboardPlayerValues_Column1value" },
        { "kind": "block", "type": "mod_SetScoreboardSorting_Reversesorting" },
        { "kind": "block", "type": "mod_SetScoreboardSorting_Sortingcolumn" },
        { "kind": "block", "type": "mod_SetScoreboardType" },
        { "kind": "block", "type": "mod_AddUIButton_Anchor" },
        { "kind": "block", "type": "mod_AddUIButton_Receiver" },
        { "kind": "block", "type": "mod_AddUIButton_Focusedalpha" },
        { "kind": "block", "type": "mod_AddUIContainer_Anchor" },
        { "kind": "block", "type": "mod_AddUIContainer_Receiver" },
        { "kind": "block", "type": "mod_AddUIContainer_Bgfill" },
        { "kind": "block", "type": "mod_AddUIGadgetImage_Parent" },
        { "kind": "block", "type": "mod_AddUIGadgetImage_Visibility" },
        { "kind": "block", "type": "mod_AddUIImage_Imagetype" },
        { "kind": "block", "type": "mod_AddUIImage_Receiver" },
        { "kind": "block", "type": "mod_AddUIImage_Imagealpha" },
        { "kind": "block", "type": "mod_AddUIText_Message" },
        { "kind": "block", "type": "mod_AddUIText_Receiver" },
        { "kind": "block", "type": "mod_AddUIText_Textanchor" },
        { "kind": "block", "type": "mod_AddUIWeaponImage_Parent" },
        { "kind": "block", "type": "mod_AddUIWeaponImage_Weaponpackage" },
        { "kind": "block", "type": "mod_AddUIWeaponImage_Visibility" },
        { "kind": "block", "type": "mod_DeleteAllUIWidgets" },
        { "kind": "block", "type": "mod_DeleteUIWidget" },
        { "kind": "block", "type": "mod_EnableUIButtonEvent" },
        { "kind": "block", "type": "mod_EnableUIInputMode_Enabled" },
        { "kind": "block", "type": "mod_EnableUIInputMode_Receiver" },
        { "kind": "block", "type": "mod_SetUIButtonAlphaBase" },
        { "kind": "block", "type": "mod_SetUIButtonAlphaDisabled" },
        { "kind": "block", "type": "mod_SetUIButtonAlphaFocused" },
        { "kind": "block", "type": "mod_SetUIButtonAlphaHover" },
        { "kind": "block", "type": "mod_SetUIButtonAlphaPressed" },
        { "kind": "block", "type": "mod_SetUIButtonColorBase" },
        { "kind": "block", "type": "mod_SetUIButtonColorDisabled" },
        { "kind": "block", "type": "mod_SetUIButtonColorFocused" },
        { "kind": "block", "type": "mod_SetUIButtonColorHover" },
        { "kind": "block", "type": "mod_SetUIButtonColorPressed" },
        { "kind": "block", "type": "mod_SetUIButtonEnabled" },
        { "kind": "block", "type": "mod_SetUIImageAlpha" },
        { "kind": "block", "type": "mod_SetUIImageColor" },
        { "kind": "block", "type": "mod_SetUIImageType" },
        { "kind": "block", "type": "mod_SetUITextAlpha" },
        { "kind": "block", "type": "mod_SetUITextAnchor" },
        { "kind": "block", "type": "mod_SetUITextColor" },
        { "kind": "block", "type": "mod_SetUITextLabel" },
        { "kind": "block", "type": "mod_SetUITextSize" },
        { "kind": "block", "type": "mod_SetUIWidgetAnchor" },
        { "kind": "block", "type": "mod_SetUIWidgetBgAlpha" },
        { "kind": "block", "type": "mod_SetUIWidgetBgColor" },
        { "kind": "block", "type": "mod_SetUIWidgetBgFill" },
        { "kind": "block", "type": "mod_SetUIWidgetDepth" },
        { "kind": "block", "type": "mod_SetUIWidgetName" },
        { "kind": "block", "type": "mod_SetUIWidgetPadding" },
        { "kind": "block", "type": "mod_SetUIWidgetParent" },
        { "kind": "block", "type": "mod_SetUIWidgetPosition" },
        { "kind": "block", "type": "mod_SetUIWidgetSize" },
        { "kind": "block", "type": "mod_SetUIWidgetVisible" }
      ]
    },
    {
      "kind": "category",
      "name": "VEHICLES",
      "colour": "#FFEB3B",
      "contents": [
        { "kind": "block", "type": "SPAWNVEHICLE" },
        { "kind": "block", "type": "DESPAWNVEHICLE" },
        { "kind": "block", "type": "damage_vehicle" },
        { "kind": "block", "type": "destroy_vehicle" },
        { "kind": "block", "type": "force_all_exit_vehicle" },
        { "kind": "block", "type": "force_player_exit_vehicle" },
        { "kind": "block", "type": "force_player_to_seat" },
        { "kind": "block", "type": "repair_vehicle" },
        { "kind": "block", "type": "set_vehicle_max_health_multiplier" },
        { "kind": "block", "type": "mod_ForceVehicleSpawnerSpawn" },
        { "kind": "block", "type": "mod_SetMaxVehicleHeightLimitScale" },
        { "kind": "block", "type": "mod_SetVehicleSpawnerAbandonVehiclesOutOfCombatArea" },
        { "kind": "block", "type": "mod_SetVehicleSpawnerApplyDamageToAbandonVehicle" },
        { "kind": "block", "type": "mod_SetVehicleSpawnerAutoSpawn" },
        { "kind": "block", "type": "mod_SetVehicleSpawnerKeepAliveAbandonRadius" },
        { "kind": "block", "type": "mod_SetVehicleSpawnerKeepAliveSpawnerRadius" },
        { "kind": "block", "type": "mod_SetVehicleSpawnerRespawnTime" },
        { "kind": "block", "type": "mod_SetVehicleSpawnerTimeUntilAbandon" },
        { "kind": "block", "type": "mod_SetVehicleSpawnerVehicleType" },
        { "kind": "block", "type": "mod_SetVehicleMaxHealthMultiplier" },
        { "kind": "block", "type": "mod_ForcePlayerExitVehicle_Vehicle" },
        { "kind": "block", "type": "mod_ForcePlayerToSeat" }
      ]
    },

    // --- GREEN MENUS (Values) ---
    {
      "kind": "category",
      "name": "AI",
      "colour": "#4CAF50",
      "contents": [
        { "kind": "block", "type": "GETAIHEALTH" },
        { "kind": "block", "type": "GETAITEAM" },
        { "kind": "block", "type": "AIISALIVE" }
      ]
    },
    {
      "kind": "category",
      "name": "ARRAYS",
      "colour": "#4CAF50",
      "contents": [
        { "kind": "block", "type": "ARRAYLENGTH" },
        { "kind": "block", "type": "GETELEMENT" },
        { "kind": "block", "type": "FINDFIRST" },
        { "kind": "block", "type": "ARRAYCONTAINS" },
        { "kind": "block", "type": "ARRAYSLICE" },
        { "kind": "block", "type": "COUNTOF" },
        { "kind": "block", "type": "append_to_array" },
        { "kind": "block", "type": "array_contains" },
        { "kind": "block", "type": "array_slice" },
        { "kind": "block", "type": "count_of" },
        { "kind": "block", "type": "current_array_element" },
        { "kind": "block", "type": "empty_array" },
        { "kind": "block", "type": "filtered_array" },
        { "kind": "block", "type": "first_of" },
        { "kind": "block", "type": "index_of_array_value" },
        { "kind": "block", "type": "last_of" },
        { "kind": "block", "type": "mapped_array" },
        { "kind": "block", "type": "random_value_in_array" },
        { "kind": "block", "type": "randomized_array" },
        { "kind": "block", "type": "sorted_array" },
        { "kind": "block", "type": "value_in_array" },
        { "kind": "block", "type": "mod_AppendToArray" },
        { "kind": "block", "type": "mod_ArraySlice" },
        { "kind": "block", "type": "mod_CountOf" },
        { "kind": "block", "type": "mod_EmptyArray" },
        { "kind": "block", "type": "mod_FirstOf" },
        { "kind": "block", "type": "mod_LastOf" },
        { "kind": "block", "type": "mod_RandomValueInArray" },
        { "kind": "block", "type": "mod_RandomizedArray" },
        { "kind": "block", "type": "mod_SortedArray" },
        { "kind": "block", "type": "mod_ValueInArray" },
        { "kind": "block", "type": "mod_AllCapturePoints" },
        { "kind": "block", "type": "mod_GetPlayersOnPoint" },
        { "kind": "block", "type": "mod_AllPlayers" },
        { "kind": "block", "type": "mod_AllVehicles" },
        { "kind": "block", "type": "mod_GetAllPlayersInVehicle" }
      ]
    },
    {
      "kind": "category",
      "name": "AUDIO",
      "colour": "#4CAF50",
      "contents": [
        { "kind": "block", "type": "locational_sounds" },
        { "kind": "block", "type": "sounds" },
        { "kind": "block", "type": "voice_overs" },
        { "kind": "block", "type": "mod_GetVO" },
        { "kind": "block", "type": "mod_GetSFX" }
      ]
    },
    {
      "kind": "category",
      "name": "EFFECTS",
      "colour": "#4CAF50",
      "contents": [
        { "kind": "block", "type": "mod_GetScreenEffect" },
        { "kind": "block", "type": "mod_GetVFX" }
      ]
    },
    {
      "kind": "category",
      "name": "EVENT PAYLOADS",
      "colour": "#4CAF50",
      "contents": [
        { "kind": "block", "type": "EVENTATTACKER" },
        { "kind": "block", "type": "EVENTDAMAGE" },
        { "kind": "block", "type": "EVENTLOCATION" },
        { "kind": "block", "type": "EVENTPLAYER" },
        { "kind": "block", "type": "EVENTTEAM" },
        { "kind": "block", "type": "EVENTVICTIM" },
        { "kind": "block", "type": "EVENTWEAPON" },
        { "kind": "block", "type": "event_capture_point" },
        { "kind": "block", "type": "event_damage_type" },
        { "kind": "block", "type": "event_death_type" },
        { "kind": "block", "type": "event_mcom" },
        { "kind": "block", "type": "event_other_player" },
        { "kind": "block", "type": "event_player" },
        { "kind": "block", "type": "event_seat" },
        { "kind": "block", "type": "event_team" },
        { "kind": "block", "type": "event_vehicle" },
        { "kind": "block", "type": "event_weapon" },
        { "kind": "block", "type": "mod_EventDamageTypeCompare" },
        { "kind": "block", "type": "mod_EventDeathTypeCompare" }
      ]
    },
    {
      "kind": "category",
      "name": "GAMEPLAY",
      "colour": "#4CAF50",
      "contents": [
        { "kind": "block", "type": "GETGAMEMODE" },
        { "kind": "block", "type": "GETSCORE" },
        { "kind": "block", "type": "GETTIMELIMIT" },
        { "kind": "block", "type": "get_game_mode_score" },
        { "kind": "block", "type": "get_game_mode_target_score" },
        { "kind": "block", "type": "get_game_mode_time_elapsed" },
        { "kind": "block", "type": "get_game_mode_time_limit" },
        { "kind": "block", "type": "get_game_mode_time_remaining" },
        { "kind": "block", "type": "get_remaining_fuse_time" },
        { "kind": "block", "type": "mod_GetGameModeScore" },
        { "kind": "block", "type": "mod_GetMatchTimeElapsed" },
        { "kind": "block", "type": "mod_GetMatchTimeRemaining" },
        { "kind": "block", "type": "mod_GetRingOfFire" },
        { "kind": "block", "type": "mod_GetRoundTime" },
        { "kind": "block", "type": "mod_GetTargetScore" }
      ]
    },
    {
      "kind": "category",
      "name": "LOGIC",
      "colour": "#4CAF50",
      "contents": [
        { "kind": "block", "type": "EQUAL" },
        { "kind": "block", "type": "NOTEQUAL" },
        { "kind": "block", "type": "LESSTHAN" },
        { "kind": "block", "type": "LESSTHANOREQUAL" },
        { "kind": "block", "type": "GREATERTHAN" },
        { "kind": "block", "type": "GREATERTHANOREQUAL" },
        { "kind": "block", "type": "AND" },
        { "kind": "block", "type": "and" },
        { "kind": "block", "type": "equals" },
        { "kind": "block", "type": "greater_than" },
        { "kind": "block", "type": "greater_than_equal_to" },
        { "kind": "block", "type": "if_then_else" },
        { "kind": "block", "type": "is_true_for_all" },
        { "kind": "block", "type": "is_true_for_any" },
        { "kind": "block", "type": "less_than" },
        { "kind": "block", "type": "less_than_equal_to" },
        { "kind": "block", "type": "not" },
        { "kind": "block", "type": "not_equal_to" },
        { "kind": "block", "type": "or" },
        { "kind": "block", "type": "xor" },
        { "kind": "block", "type": "mod_And" },
        { "kind": "block", "type": "mod_Equals" },
        { "kind": "block", "type": "mod_GreaterThan" },
        { "kind": "block", "type": "mod_GreaterThanEqualTo" },
        { "kind": "block", "type": "mod_IfThenElse" },
        { "kind": "block", "type": "mod_IsType" },
        { "kind": "block", "type": "mod_LessThan" },
        { "kind": "block", "type": "mod_LessThanEqualTo" },
        { "kind": "block", "type": "mod_Not" },
        { "kind": "block", "type": "mod_NotEqualTo" },
        { "kind": "block", "type": "mod_Or" },
        { "kind": "block", "type": "mod_Xor" }
      ]
    },
    {
      "kind": "category",
      "name": "MATH",
      "colour": "#4CAF50",
      "contents": [
        { "kind": "block", "type": "ADD" },
        { "kind": "block", "type": "SUBTRACT" },
        { "kind": "block", "type": "MULTIPLY" },
        { "kind": "block", "type": "DIVIDE" },
        { "kind": "block", "type": "POWER" },
        { "kind": "block", "type": "SQUAREROOT" },
        { "kind": "block", "type": "ABSOLUTE" },
        { "kind": "block", "type": "MODULO" },
        { "kind": "block", "type": "ARCCOSINEINDEGREES" },
        { "kind": "block", "type": "ARCCOSINEINRADIANS" },
        { "kind": "block", "type": "ARCSINEINDEGREES" },
        { "kind": "block", "type": "ARCSINEINRADIANS" },
        { "kind": "block", "type": "ARCTANGENTINDEGREES" },
        { "kind": "block", "type": "ARCTANGENTINRADIANS" },
        { "kind": "block", "type": "CEILING" },
        { "kind": "block", "type": "COSINEFROMDEGREES" },
        { "kind": "block", "type": "COSINEFROMRADIANS" },
        { "kind": "block", "type": "absolute_value" },
        { "kind": "block", "type": "add" },
        { "kind": "block", "type": "angle_between_vectors" },
        { "kind": "block", "type": "angle_difference" },
        { "kind": "block", "type": "arccosine_in_degrees" },
        { "kind": "block", "type": "arccosine_in_radians" },
        { "kind": "block", "type": "arcsine_in_degrees" },
        { "kind": "block", "type": "arcsine_in_radians" },
        { "kind": "block", "type": "arctangent_in_degrees" },
        { "kind": "block", "type": "arctangent_in_radians" },
        { "kind": "block", "type": "ceiling" },
        { "kind": "block", "type": "cosine_from_degrees" },
        { "kind": "block", "type": "cosine_from_radians" },
        { "kind": "block", "type": "cross_product" },
        { "kind": "block", "type": "distance_between" },
        { "kind": "block", "type": "divide" },
        { "kind": "block", "type": "dot_product" },
        { "kind": "block", "type": "floor" },
        { "kind": "block", "type": "max" },
        { "kind": "block", "type": "modulo" },
        { "kind": "block", "type": "multiply" },
        { "kind": "block", "type": "pi" },
        { "kind": "block", "type": "raise_to_power" },
        { "kind": "block", "type": "random_real" },
        { "kind": "block", "type": "round_to_integer" },
        { "kind": "block", "type": "sine_from_degrees" },
        { "kind": "block", "type": "sine_from_radians" },
        { "kind": "block", "type": "square_root" },
        { "kind": "block", "type": "subtract" },
        { "kind": "block", "type": "tangent_from_degrees" },
        { "kind": "block", "type": "tangent_from_radians" },
        { "kind": "block", "type": "mod_AbsoluteValue" },
        { "kind": "block", "type": "mod_Add" },
        { "kind": "block", "type": "mod_AngleBetweenVectors" },
        { "kind": "block", "type": "mod_AngleDifference" },
        { "kind": "block", "type": "mod_ArccosineInDegrees" },
        { "kind": "block", "type": "mod_ArccosineInRadians" },
        { "kind": "block", "type": "mod_ArcsineInDegrees" },
        { "kind": "block", "type": "mod_ArcsineInRadians" },
        { "kind": "block", "type": "mod_ArctangentInDegrees" },
        { "kind": "block", "type": "mod_ArctangentInRadians" },
        { "kind": "block", "type": "mod_Ceiling" },
        { "kind": "block", "type": "mod_CosineFromDegrees" },
        { "kind": "block", "type": "mod_CosineFromRadians" },
        { "kind": "block", "type": "mod_DegreesToRadians" },
        { "kind": "block", "type": "mod_DistanceBetween" },
        { "kind": "block", "type": "mod_Divide" },
        { "kind": "block", "type": "mod_DotProduct" },
        { "kind": "block", "type": "mod_Floor" },
        { "kind": "block", "type": "mod_Max" },
        { "kind": "block", "type": "mod_Modulo" },
        { "kind": "block", "type": "mod_Multiply" },
        { "kind": "block", "type": "mod_Pi" },
        { "kind": "block", "type": "mod_RadiansToDegrees" },
        { "kind": "block", "type": "mod_RaiseToPower" },
        { "kind": "block", "type": "mod_RandomReal" },
        { "kind": "block", "type": "mod_RoundToInteger" },
        { "kind": "block", "type": "mod_SineFromDegrees" },
        { "kind": "block", "type": "mod_SineFromRadians" },
        { "kind": "block", "type": "mod_SquareRoot" },
        { "kind": "block", "type": "mod_Subtract" },
        { "kind": "block", "type": "mod_TangentFromDegrees" },
        { "kind": "block", "type": "mod_TangentFromRadians" }
      ]
    },
    {
      "kind": "category",
      "name": "OBJECTIVE",
      "colour": "#4CAF50",
      "contents": [
        { "kind": "block", "type": "CAPTUREPOINTS" },
        { "kind": "block", "type": "COMPARECAPTUREPOINT" },
        { "kind": "block", "type": "capture_points" },
        { "kind": "block", "type": "compare_capture_point" },
        { "kind": "block", "type": "get_all_capture_points" },
        { "kind": "block", "type": "get_all_mco_ms" },
        { "kind": "block", "type": "get_capture_point_position" },
        { "kind": "block", "type": "get_capture_progress" },
        { "kind": "block", "type": "get_mcom_state" },
        { "kind": "block", "type": "get_objective" },
        { "kind": "block", "type": "mco_ms" },
        { "kind": "block", "type": "mod_AllCapturePoints" },
        { "kind": "block", "type": "mod_GetCapturePoint" },
        { "kind": "block", "type": "mod_GetCaptureProgress" },
        { "kind": "block", "type": "mod_GetCurrentOwnerTeam" },
        { "kind": "block", "type": "mod_GetOwnerProgressTeam" },
        { "kind": "block", "type": "mod_GetPlayersOnPoint" },
        { "kind": "block", "type": "mod_GetPreviousOwnerTeam" },
        { "kind": "block", "type": "mod_GetHQ" },
        { "kind": "block", "type": "mod_GetMCOM" },
        { "kind": "block", "type": "mod_GetSector" }
      ]
    },
    {
      "kind": "category",
      "name": "OTHER",
      "colour": "#4CAF50",
      "contents": [
        { "kind": "block", "type": "BOOL" },
        { "kind": "block", "type": "bool" },
        { "kind": "block", "type": "condition" },
        { "kind": "block", "type": "custom_message_slot" },
        { "kind": "block", "type": "message" },
        { "kind": "block", "type": "mcom_state_bool" },
        { "kind": "block", "type": "med_gadget_types" },
        { "kind": "block", "type": "mod_GetObjId" }
      ]
    },
    {
      "kind": "category",
      "name": "PLAYER",
      "colour": "#4CAF50",
      "contents": [
        { "kind": "block", "type": "CLOSESTPLAYERTO" },
        { "kind": "block", "type": "closest_player_to" },
        { "kind": "block", "type": "farthest_player_from" },
        { "kind": "block", "type": "get_all_players_in_vehicle" },
        { "kind": "block", "type": "get_current_owner_team_id" },
        { "kind": "block", "type": "get_inventory_ammo" },
        { "kind": "block", "type": "get_inventory_magazine_ammo" },
        { "kind": "block", "type": "get_owner_progress_team_id" },
        { "kind": "block", "type": "get_player_deaths" },
        { "kind": "block", "type": "get_player_from_vehicle_seat" },
        { "kind": "block", "type": "get_player_kills" },
        { "kind": "block", "type": "get_player_state" },
        { "kind": "block", "type": "get_player_vehicle_seat" },
        { "kind": "block", "type": "get_players" },
        { "kind": "block", "type": "get_players_on_point" },
        { "kind": "block", "type": "get_previous_owner_team_id" },
        { "kind": "block", "type": "get_team_id" },
        { "kind": "block", "type": "get_vehicle_from_player" },
        { "kind": "block", "type": "get_vehicle_team_id" },
        { "kind": "block", "type": "has_inventory" },
        { "kind": "block", "type": "inventory_character_specialties" },
        { "kind": "block", "type": "inventory_class_gadgets" },
        { "kind": "block", "type": "inventory_melee_weapons" },
        { "kind": "block", "type": "inventory_open_gadgets" },
        { "kind": "block", "type": "inventory_primary_weapons" },
        { "kind": "block", "type": "inventory_secondary_weapons" },
        { "kind": "block", "type": "inventory_throwables" },
        { "kind": "block", "type": "is_inventory_slot_active" },
        { "kind": "block", "type": "is_killer_weapon" },
        { "kind": "block", "type": "is_player_using_soldier" },
        { "kind": "block", "type": "is_player_valid" },
        { "kind": "block", "type": "is_victim_damage_type" },
        { "kind": "block", "type": "is_victim_death_type" },
        { "kind": "block", "type": "med_gadget_types" },
        { "kind": "block", "type": "player_inventory_slots" },
        { "kind": "block", "type": "player_soldiers" },
        { "kind": "block", "type": "player_state_bool" },
        { "kind": "block", "type": "player_state_number" },
        { "kind": "block", "type": "player_state_vector" },
        { "kind": "block", "type": "resupply_types" },
        { "kind": "block", "type": "mod_ClosestPlayerTo_Vector" },
        { "kind": "block", "type": "mod_ClosestPlayerTo_Team" },
        { "kind": "block", "type": "mod_FarthestPlayerFrom_Vector" },
        { "kind": "block", "type": "mod_FarthestPlayerFrom_Team" },
        { "kind": "block", "type": "mod_GetPlayerDeaths" },
        { "kind": "block", "type": "mod_GetPlayerKills" },
        { "kind": "block", "type": "mod_GetSquad_Player" },
        { "kind": "block", "type": "mod_GetSquad_Squadidnumber" },
        { "kind": "block", "type": "mod_GetTeam" },
        { "kind": "block", "type": "mod_IsPlayerValid" },
        { "kind": "block", "type": "mod_GetInventoryAmmo" },
        { "kind": "block", "type": "mod_GetInventoryMagazineAmmo" },
        { "kind": "block", "type": "mod_GetSoldierState" },
        { "kind": "block", "type": "mod_HasEquipment" },
        { "kind": "block", "type": "mod_IsInventorySlotActive" },
        { "kind": "block", "type": "mod_IsSoldierClass" }
      ]
    },
    {
      "kind": "category",
      "name": "TRANSFORM",
      "colour": "#4CAF50",
      "contents": [
        { "kind": "block", "type": "BACKWARDVECTOR" },
        { "kind": "block", "type": "backward_vector" },
        { "kind": "block", "type": "create_vector" },
        { "kind": "block", "type": "degrees_to_radians" },
        { "kind": "block", "type": "direction_from_angles" },
        { "kind": "block", "type": "direction_towards" },
        { "kind": "block", "type": "down_vector" },
        { "kind": "block", "type": "forward_vector" },
        { "kind": "block", "type": "get_x_component" },
        { "kind": "block", "type": "get_y_component" },
        { "kind": "block", "type": "get_z_component" },
        { "kind": "block", "type": "left_vector" },
        { "kind": "block", "type": "local_to_world_position" },
        { "kind": "block", "type": "local_to_world_vector" },
        { "kind": "block", "type": "normalize" },
        { "kind": "block", "type": "radians_to_degrees" },
        { "kind": "block", "type": "right_vector" },
        { "kind": "block", "type": "up_vector" },
        { "kind": "block", "type": "vector_towards" },
        { "kind": "block", "type": "world_to_local_position" },
        { "kind": "block", "type": "world_to_local_vector" },
        { "kind": "block", "type": "mod_CreateTransform" },
        { "kind": "block", "type": "mod_CreateVector" },
        { "kind": "block", "type": "mod_CrossProduct" },
        { "kind": "block", "type": "mod_DegreesToRadians" },
        { "kind": "block", "type": "mod_DirectionFromAngles" },
        { "kind": "block", "type": "mod_DirectionTowards" },
        { "kind": "block", "type": "mod_Normalize" },
        { "kind": "block", "type": "mod_BackwardVector" },
        { "kind": "block", "type": "mod_DownVector" },
        { "kind": "block", "type": "mod_ForwardVector" },
        { "kind": "block", "type": "mod_GetObjectPosition" },
        { "kind": "block", "type": "mod_GetObjectRotation" },
        { "kind": "block", "type": "mod_GetObjectTransform" },
        { "kind": "block", "type": "mod_LeftVector" },
        { "kind": "block", "type": "mod_LocalPositionOf" },
        { "kind": "block", "type": "mod_LocalVectorOf" },
        { "kind": "block", "type": "mod_RightVector" },
        { "kind": "block", "type": "mod_UpVector" },
        { "kind": "block", "type": "mod_VectorTowards" },
        { "kind": "block", "type": "mod_WorldPositionOf" },
        { "kind": "block", "type": "mod_WorldVectorOf" },
        { "kind": "block", "type": "mod_XComponentOf" },
        { "kind": "block", "type": "mod_YComponentOf" },
        { "kind": "block", "type": "mod_ZComponentOf" }
      ]
    },
    {
      "kind": "category",
      "name": "USER INTERFACE",
      "colour": "#4CAF50",
      "contents": [
        { "kind": "block", "type": "world_icon_images" },
        { "kind": "block", "type": "world_icons" },
        { "kind": "block", "type": "mod_GetWorldIcon" },
        { "kind": "block", "type": "mod_Message_Msgarg2" },
        { "kind": "block", "type": "mod_Message_Msgarg1" },
        { "kind": "block", "type": "mod_Message_Msgarg0" },
        { "kind": "block", "type": "mod_Message_Msg" },
        { "kind": "block", "type": "mod_FindUIWidgetWithName_Searchroot" },
        { "kind": "block", "type": "mod_FindUIWidgetWithName_Name" },
        { "kind": "block", "type": "mod_GetUIButtonAlphaBase" },
        { "kind": "block", "type": "mod_GetUIButtonAlphaDisabled" },
        { "kind": "block", "type": "mod_GetUIButtonAlphaFocused" },
        { "kind": "block", "type": "mod_GetUIButtonAlphaHover" },
        { "kind": "block", "type": "mod_GetUIButtonAlphaPressed" },
        { "kind": "block", "type": "mod_GetUIButtonColorBase" },
        { "kind": "block", "type": "mod_GetUIButtonColorDisabled" },
        { "kind": "block", "type": "mod_GetUIButtonColorFocused" },
        { "kind": "block", "type": "mod_GetUIButtonColorHover" },
        { "kind": "block", "type": "mod_GetUIButtonColorPressed" },
        { "kind": "block", "type": "mod_GetUIButtonEnabled" },
        { "kind": "block", "type": "mod_GetUIImageAlpha" },
        { "kind": "block", "type": "mod_GetUIImageColor" },
        { "kind": "block", "type": "mod_GetUIImageType" },
        { "kind": "block", "type": "mod_GetUIRoot" },
        { "kind": "block", "type": "mod_GetUITextAlpha" },
        { "kind": "block", "type": "mod_GetUITextAnchor" },
        { "kind": "block", "type": "mod_GetUITextColor" },
        { "kind": "block", "type": "mod_GetUITextSize" },
        { "kind": "block", "type": "mod_GetUIWidgetAnchor" },
        { "kind": "block", "type": "mod_GetUIWidgetBgAlpha" },
        { "kind": "block", "type": "mod_GetUIWidgetBgColor" },
        { "kind": "block", "type": "mod_GetUIWidgetBgFill" },
        { "kind": "block", "type": "mod_GetUIWidgetDepth" },
        { "kind": "block", "type": "mod_GetUIWidgetName" },
        { "kind": "block", "type": "mod_GetUIWidgetPadding" },
        { "kind": "block", "type": "mod_GetUIWidgetParent" },
        { "kind": "block", "type": "mod_GetUIWidgetPosition" },
        { "kind": "block", "type": "mod_GetUIWidgetSize" },
        { "kind": "block", "type": "mod_GetUIWidgetVisible" },
        { "kind": "block", "type": "mod_HasUIWidgetWithName_Searchroot" },
        { "kind": "block", "type": "mod_HasUIWidgetWithName_Name" }
      ]
    },
    {
      "kind": "category",
      "name": "VEHICLES",
      "colour": "#4CAF50",
      "contents": [
        { "kind": "block", "type": "VEHICLE_LIST_ITEM" },
        { "kind": "block", "type": "COMPAREVEHICLENAME" },
        { "kind": "block", "type": "compare_vehicle_name" },
        { "kind": "block", "type": "get_all_vehicles" },
        { "kind": "block", "type": "get_seat_count" },
        { "kind": "block", "type": "get_vehicle_state" },
        { "kind": "block", "type": "is_vehicle_occupied" },
        { "kind": "block", "type": "is_vehicle_seat_occupied" },
        { "kind": "block", "type": "vehicle_state_vector" },
        { "kind": "block", "type": "vehicle_types" },
        { "kind": "block", "type": "vehicles" },
        { "kind": "block", "type": "mod_AllVehicles" },
        { "kind": "block", "type": "mod_CompareVehicleName" },
        { "kind": "block", "type": "mod_GetVehicleFromPlayer" },
        { "kind": "block", "type": "mod_GetVehicleSeatCount" },
        { "kind": "block", "type": "mod_GetVehicleState" },
        { "kind": "block", "type": "mod_GetVehicleTeam" },
        { "kind": "block", "type": "mod_IsVehicleOccupied" },
        { "kind": "block", "type": "mod_IsVehicleSeatOccupied" },
        { "kind": "block", "type": "mod_GetAllPlayersInVehicle" },
        { "kind": "block", "type": "mod_GetPlayerFromVehicleSeat" },
        { "kind": "block", "type": "mod_GetPlayerVehicleSeat" }
      ]
    },
    {
      "kind": "category",
      "name": "SELECTION LISTS",
      "colour": "#4CAF50",
      "custom": "SELECTION_LISTS_CATEGORY",
      "contents": [
        { "kind": "block", "type": "damage_types" },
        { "kind": "block", "type": "death_types" },
        { "kind": "block", "type": "factions" },
        { "kind": "block", "type": "input_restrictions" },
        { "kind": "block", "type": "is_current_map" },
        { "kind": "block", "type": "is_faction" },
        { "kind": "block", "type": "is_type" },
        { "kind": "block", "type": "maps" },
        { "kind": "block", "type": "types" }
      ]
    },
    {
      "kind": "category",
      "name": "LITERALS",
      "colour": "#4CAF50",
      "contents": [
        { "kind": "block", "type": "BOOLEAN" },
        { "kind": "block", "type": "NUMBER" },
        { "kind": "block", "type": "STRING" },
        { "kind": "block", "type": "bool" },
        { "kind": "block", "type": "number" },
        { "kind": "block", "type": "string" },
        { "kind": "block", "type": "mod_CreateNewWeaponPackage" }
      ]
    },
    {
      "kind": "category",
      "name": "VARIABLES",
      "colour": "#4CAF50",
      "custom": "VARIABLES_CATEGORY",
      "contents": []
    },
    {
      "kind": "category",
      "name": "SUBROUTINES",
      "colour": "#E6A85C",
      "custom": "SUBROUTINES_CATEGORY",
      "contents": []
    },
    {
      "kind": "category",
      "name": "CONTROL ACTIONS",
      "colour": "#0288D1",
      "contents": [
        { "kind": "block", "type": "WAIT" },
        { "kind": "block", "type": "WAITUNTIL" },
        { "kind": "block", "type": "ABORT" },
        { "kind": "block", "type": "AbortIf" },
        { "kind": "block", "type": "BREAK" },
        { "kind": "block", "type": "CONTINUE" },
        { "kind": "block", "type": "IF" },
        { "kind": "block", "type": "WHILE" },

        { "kind": "block", "type": "abort" },
        { "kind": "block", "type": "abort_if" },
        { "kind": "block", "type": "break" },
        { "kind": "block", "type": "continue" },
        { "kind": "block", "type": "else_if" },
        { "kind": "block", "type": "if" },
        { "kind": "block", "type": "skip" },
        { "kind": "block", "type": "skip_if" },
        { "kind": "block", "type": "wait" },
        { "kind": "block", "type": "wait_until" },
        { "kind": "block", "type": "while" }
      ]
    }
  ]
};